### ISSUE TITLE
Visualize Heatmaps within OncoPrints

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#1]
**Background**: An OncoPrint is a concise and compact graphical summary of genomic alterations in multiple genes across a set of tumor samples. Rows represent genes, and columns represent samples. Glyphs and color coding are used to summarize distinct genomic alterations including mutations, CNAs (amplifications and homozygous deletions), and changes in gene expression or protein abundance.  An OncoPrint can also visualize clinical data.

![image](https://cloud.githubusercontent.com/assets/840895/12486711/ce810f86-c031-11e5-93cb-79387b918f24.png)

**Goal**: Support heat map visualization of a set of genes in OncoPrint

**Approach**: Using D3js and/or WebGL to plot heatmap of continuous data (mRNA/miRNA/protein expression, copy number, methylation) as a section in OncoPrint. Optionally, support hierarchical clustering.

**Need skills**: Javascript, D3js, WebGL

**Possible mentors**: [Adam Abeshouse](https://github.com/adamabeshouse), [JJ Gao](https://github.com/jjgao)

**Comment by crystal95** [comment]
Hi JianJiong Gao , 

This project looks quite interesting to me . I am interested to take part in GSOC16 . I am third year undergraduate from IIIT-Hyderabad and have proficient coding skills . Can you please guide me on how can I proceed with the project . thanks in advance :)

**Comment by jjgao** [comment]
Hi @crystal95: You would need to learn [Oncoprint.js](https://github.com/cBioPortal/oncoprintjs) and the concept of [heatmap](https://www.google.com/search?q=expression+heatmap&tbm=isch).

@adamabeshouse may be able to provide more information on Oncoprint.js.

**Comment by crystal95** [comment]
@jjgao Thanks alot for responding . Can you please tell if "Support of heat map in OncoPrint " is a potential project for GSOC16 
@adamabeshouse Can you please guide me about how to start with Oncoprint.js  .  

Thanks

**Comment by jjgao** [comment]
@crystal95 yes, it is a potential project for GSoC16.

**Comment by crystal95** [comment]
Thank you :) 
project looks quite interesting and I am eagerly waiting to start working on it :)

**Comment by adamabeshouse** [comment]
Hi @crystal95, thanks for your interest! The code for oncoprint.js is currently in development, but will be released quite soon, in the next couple of weeks. We will post back here to let you know when that's the case :smile: !

**Comment by crystal95** [comment]
@adamabeshouse 
Thanks for your response :)
I am interested in taking part in GSOC16 . Can you plz suggest how can I start with the project ? Any specific tutorials or language you could suggest me till then :D 

thanks

**Comment by jjgao** [comment]
@crystal95: @adamabeshouse will put more doc in the Oncoprint.js project for you to build very soon. For the moment, [the cBioPortal paper](http://www.ncbi.nlm.nih.gov/pubmed/23550210) might be a good start for you to understand Oncoprint. You can also try to [run the cBioPortal code](https://github.com/cBioPortal/cbioportal/wiki) and play with the oncoprint code there. The code is under `js/src/oncoprint/`.

**Comment by adamabeshouse** [comment]
Hi @crystal95, I've just finished putting the code up at https://github.com/cBioPortal/oncoprintjs

Please don't hesitate to let me know if you have any questions! :)

**Comment by crystal95** [comment]
@jjgao @adamabeshouse Thanks alot people :D 

Will get back to you once I go through the mentioned stuff !!

Thanks alot for detailed responses :)

**Comment by crystal95** [comment]
@adamabeshouse 
White I run " gulp test " , I get following error : 


[14:20:15] Using gulpfile ~/oncoprintjs-master/src/gulpfile.js
[14:20:15] Starting 'test'...
/bin/sh: 1: browserify: not found
[14:20:15] 'test' errored after 19 ms
[14:20:15] Error: Command `browserify test.js -o oncoprint-test-bundle.js` failed with exit code 127
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:117:20)
    at Pipe.close (net.js:451:12)
 
Can you tell how can I resolve it ?

**Comment by adamabeshouse** [comment]
@crystal95 ah yes, sorry, you also need to install browserify
