### ISSUE TITLE
Small typo mistake in README

### ISSUE THREAD

**Issue by muhammedanaskhan** [cBioPortal/GSoC#104]
**Background**: Typo in README

**Goal**: Correct small typo in readme

![cbio_readme_issue](https://github.com/cBioPortal/GSoC/assets/72510634/8fcfb741-3076-48e1-8d60-8cefa5f3a62a)

**Comment by Meena7681** [comment]
fixed  #104

**Comment by inodb** [comment]
Thanks for reporting @muhammedanaskhan and for fixing @Meena7681 !
