### ISSUE TITLE
Visualize BAM files and SEG files with igv.js

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#15]
**Background**: **Background**: We are using [IGV web start](https://www.broadinstitute.org/igv/) for visualization of copy number segment files in the cBioPortal. Now the IGV team has developed [igv.js](https://github.com/igvteam/igv.js), it's a good opportunity to implement a native Javascript genome viewer inside cBioPortal for viewing copy number seg data and BAM data.

![image](https://cloud.githubusercontent.com/assets/840895/12852182/affb5adc-cbfb-11e5-9843-a07dffcfaf96.png)

**Goal**: To replace IGV web start with igv.js for visualizing BAM and SEG.

**Approach**: 
- Evaluation the functionality and performance of igv.js
- Visualize SEG file with igv.js
- Visualize BAM with igv.js
- Two options for the data
  - Still load from a web resource like we are currently doing with IGV.
  - Save data to a secured database and show only local segments and alignments.

**Need skills**: Javascript

**Possible mentors**: [Benjamin Gross](https://github.com/n1zea144)

**Comment by armish** [comment]
Also of interest is [pileup.js](https://github.com/hammerlab/pileup.js) ([paper](http://biorxiv.org/content/early/2016/01/26/036962)) and I will be more than happy to help someone get this going in case using an igv.js alternative is an option.

**Comment by jjgao** [comment]
@armish sure, igv.js alternative is an option. Please feel free to sign yourself up as a potential mentor.

**Comment by armish** [comment]
thanks, @jjgao — might be hard for me to make commitments as a mentor, but happy to chime in and help you guys integrate pileup.js from the other side if there is interest :+1:

**Comment by Lakmini** [comment]
Hi,
I an undergraduate from University of Moratuwa. I am very interested on this project and I suppose that I would be able to contribute to this project.Please let me know how to proceed.

**Comment by jjgao** [comment]
@Lakmini please get your self familiar with igv / igv.js and cBioPortal and try to write a proposal based on your understanding. Please don't hesitate to contact us if you have any questions.
