### ISSUE TITLE
Cohort comparison analysis in cBioPortal

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#18]
**Background**: In the cBioPortal, the study view page provides an overview all clinical data of an cohort (a group of samples/patients), e.g. [the TCGA endometrial cancer cohort](http://www.cbioportal.org/study.do?cancer_study_id=ucec_tcga_pub). In the study view, one can select a subset of samples and do further analysis. But currently, there is no systematical way to perform comparison analysis between cohorts or sub-cohorts in the study view.

![image](https://cloud.githubusercontent.com/assets/840895/13059393/c4975aaa-d3f7-11e5-99fa-a8a288390d8a.png)

**Goal**: Develop capacity to perform comparison between cohorts or sub-cohorts, for example, to detect what are the differentially mutated genes in different stages of diseases. 

**Approach**: 
- Develop utilities for users to save / manage cohorts.
- Allow users to compare cohorts on the study view, including:
  - detecting enriched mutation or copy number events in one of the cohort.
  - detecting differentially expressed genes.
  - detecting other enriched clinical annotations.

**Need skills**: Bioinformatics, Javascript

**Possible mentors**: [Hongxin Zhang](https://github.com/zhx828), [Yichao Sun](https://github.com/yichaoS), [JJ Gao](https://github.com/jjgao)

**Comment by Verma-Ashish13** [comment]
Hello Jjgao,
I am interested in this project as an idea for Gsoc. I am having good coding background in javascript but I am not much aware about bioinformatics. Can you please suggest me,How should I start ?

**Comment by jjgao** [comment]
@Verma-Ashish13 please get yourself familiar with [this project](https://github.com/cBioPortal/iViz). It is not a big problem if you don't have bioinformatics background, but you would need some basic statistic skills.

**Comment by zhx828** [comment]
For all future candidates, as JJ mentioned above, please take a look the iViz project, specially the wiki page. Please feel free to leave any messages.

**Comment by spetluru** [comment]
Hello,
I have a few redesign ideas based on my review of current research literature examining cohort analysis. How would you recommend communication for additional clarifications and recommendations while I begin to draft my project proposal?

**Comment by zhx828** [comment]
Hi @spetluru,
Thanks for your interests! You are welcomed to post any questions in here or in our google group [link](https://groups.google.com/forum/#!forum/cbioportal-gsoc)  If you have Slack, we would love to have you in our GSoC channel as well. Please feel free to ask if you have any other questions. Thanks.

**Comment by zhx828** [comment]
@spetluru please send your email to hongxin@cbio.mskcc.org Thanks.
