### ISSUE TITLE
Improve timeline on patient view

### ISSUE THREAD

**Issue by inodb** [cBioPortal/GSoC#19]
**Background**: The [patient view page of cBioPortal](http://www.cbioportal.org/case.do?cancer_study_id=lgg_ucsf_2014&case_id=P04) shows demographic and clinical information, an overview of genomic changes in the patient's DNA samples and a timeline:

![screen shot 2016-02-11 at 5 42 45 pm](https://cloud.githubusercontent.com/assets/1334004/12993234/e927e074-d0e6-11e5-9119-b0eaec109213.png)

This particular timeline gives an overview of:
1. when surgeries have taken place
2. whether specimens were collected
3. the treatment that was received

Researchers supplying data to cBioPortal are however free to add their own custom timeline data.  Also note that the timeline does not display dates like most timelines, but only days since diagnosis.  [Our timeline implementation](https://github.com/cbioportal/clinical-timeline) builds upon the popular [d3-timeline library](https://github.com/jiahuang/d3-timeline), which displays a collection of timepoints in JSON format as a timeline. We've extended the JSON format and the API to e.g. add more information to a timepoint and show tooltips on mouseover. We would like to further improve the timeline library by adding a zoom feature, showing all information associated with a given timepoint and showing line plots on a track.

**Goal**: Improve the timeline

**Approach**: 
- Support zoom, similar to: http://bl.ocks.org/bunkat/2338034
- Show vertical line on mouseover and show all tooltips associated with the timepoints in spirit of http://square.github.io/cubism/
- Show lineplot for timepoints with associated float/integer values indicating changes over time

**Need skills**: Javascript

**Possible mentors**: [Ino de Bruijn](https://github.com/inodb)

**Comment by shuklank** [comment]
Hello, I would like to know  if this issue is part of GSOC'16 idea list . I would like to contribute in it .

**Comment by jjgao** [comment]
@shuklank: yes, it is. All open issues are part of GSOC'16 idea list

**Comment by smashmyster** [comment]
Hello,
Are we allowed to add more features maybe summarize some info in a box on the right when someone hover over some data

**Comment by jjgao** [comment]
@smashmyster sure, please feel free to propose your ideas.

**Comment by smashmyster** [comment]
Thank you.

**Comment by madhug-nadig** [comment]
Hi, should the Genomic Overview timeline also be modified?

**Comment by jjgao** [comment]
@madhug-nadig: Genomic Overview is covered in idea #6.

**Comment by madhug-nadig** [comment]
So, it is to be implemented as a separate project?

I am interested to contribute in this project. Is getting familiar with implementing d3-timeline a good start?

**Comment by inodb** [comment]
@madhug-nadig The Genomic Overview (#6) project would be separate from this timeline project. We do display them on the same patient page together eventually but we'd like to build them out as separate tools. The timeline project is already separated, the genomic overview would be starting from scratch.

If you're interested in looking at this project I can recommend starting with trying to solve some issues of the clinical timeline: https://github.com/cBioPortal/clinical-timeline/issues?q=is%3Aopen+is%3Aissue+label%3A%22Difficulty+Novice%22

**Comment by ssinghal123** [comment]
Hi. I am Shubham Singhal, a fourth year student at IIT Bombay. I would like to contribute to this project as part of GSOC 2016. 

In d3.js we have to select the portion we want to zoom into. It would be nice to zoom where our mouse is. I looked on ways to zoom using javascript. We can use various plugins for jQuery to approach the problem. This is one of plugin: http://jaukia.github.io/zoomooz/

Please let me know what do you think about it and how to proceed further to participate in this idea.

**Comment by inodb** [comment]
@ssinghal123 Please have a look at the issues in: https://github.com/cbioportal/clinical-timeline/issues. Some form of zoom is currently implemented, but ideally we would have something like this: http://bl.ocks.org/timelyportfolio/5c136de85de1c2abb6fc

**Comment by ssinghal123** [comment]
Okay. I went over the issues with timeline. Should I start with fixing some
of issues there?
ᐧ

**Comment by madhug-nadig** [comment]
@jjgao @inodb partially implemented point 2 of the implementation here: [vertical line on mouse over](https://github.com/cBioPortal/clinical-timeline/pull/65)

![vertical line](https://cloud.githubusercontent.com/assets/13866921/13691201/d827f200-e75c-11e5-879d-733df8c1360e.gif)

**Comment by inodb** [comment]
@ssinghal123 yes that would be good
@madhug-nadig Thanks. I've made some comments on your pull request https://github.com/cBioPortal/clinical-timeline/pull/65
