### ISSUE TITLE
Onco Query Language (OQL) editor

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#2]
**Background**: [The Onco Query Language (OQL)](http://www.cbioportal.org/onco_query_lang_desc.jsp) is useful for advanced genomic event query . Currently, a user have to type the OQL in the gene input box. The OQL parse won't run until the user hit Query.

**Goal**: Build a improved gene input box that
- guides a user to build OQL, e.g. after a user type in a gene and put a colon ":", list all keywords of OQL in the drop down,
- parses the input on the fly with OQL parser,
- validates genes and put warnings inside the input box (similar to http://www.genemania.org/).

**Approach**: building a standalone Javascript library for OQL parser (that is done in the portal code base) and OQL editor.

**Need skills**: Javascript

**Possible mentors**: [Adam Abeshouse](https://github.com/adamabeshouse)

**Comment by rohangoel96** [comment]
Hi @jjgao, this seems pretty interesting I would be glad if i get to work on this for GSoC '16. Please help me get started.

**Comment by jjgao** [comment]
@rohangoel96: I'd start off with getting familiar with [The Onco Query Language (OQL)](http://www.cbioportal.org/onco_query_lang_desc.jsp) and thinking about how you can build a interface for it.

**Comment by Verma-Ashish13** [comment]
I am interested on this.How should I move forward ?

**Comment by jjgao** [comment]
@Verma-Ashish13: please see my comment above. You would also need to get familiar with a few concepts in the [cBioPortal](http://www.cbioportal.org/) -- following [this paper](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4160307/) would be a good start.

**Comment by shrumit** [comment]
@jjgao @adamabeshouse
Hey I'm working on a comprehensive proposal for this project and saw that a similar task has been put in the 1.2.0 Milestone list: https://github.com/cBioPortal/cbioportal/milestones/1.2.0
(Refer to https://github.com/cBioPortal/cbioportal/issues/932)

When is 1.2.0 scheduled for released? Is this project still fair game for GSoC? I will be getting my proposal in by Wednesday. Also, do I submit a draft proposal to you directly for feedback or do can I just submit it through the GSoC system?

**Comment by jjgao** [comment]
@shrumit cBioPortal/cbioportal#932 is related but it won't have most of the component in this project. We just wanted to be able to get he genes in the frontend for gene-validation purpose.

**Comment by shrumit** [comment]
@jjgao Sounds good. I've just submitted a draft proposal for this project through GSoC. I would appreciate feedback!
