### ISSUE TITLE
Collaborative construction of cancer pathways with PathwayMapper

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/GSoC#26]
**Background**: 
While the network visualization module in cBioPortal is a powerful exploration tool, most biologists are more comfortable with the kind of simplified, curated pathway diagrams that are featured in many manuscripts from The Cancer Genome Atlas (TCGA) . With the motivation of creating a platform that provides more intuitive pathway diagrams, yet supports these with rich data ‘decoration’ and analysis with access to data in cBioPortal, with attractive visualization, we developed a tool named [PathwayMapper](https://github.com/iVis-at-Bilkent/pathway-mapper).

**Goal**: 
The goal of this project is to implement new exciting features for the second version of PathwayMapper including:
- interaction annotations (e.g. Pubmed IDs)
- expand-collapse, hide-show operations for complexity management
- filtering (by alteration percentage) and highlighting capabilities
- edge bends
- chat support for the collaborative mode
- undo support for the collaborative mode

**Approach**: 
PathwayMapper is based on [Cytoscape.js](http://js.cytoscape.org). We will try to reuse the extensions available for Cytoscape.js.

**Need skills**: 
Good programming skills is required. Experience in web technologies (JavaScript, html, css) and/or visualization software is a plus.

**Possible mentors**: 
[Ugur Dogrusoz](mailto:ugurdogrusoz@gmail.com), [Konnor C. La](lak1@mskcc.org)

**Comment by sagar-shah94** [comment]
I am interested to work on this project.i have experience in working with node js ,express.i have little bit of kowledge of D3 js for visulisation.i have already cloned pathway-mapper repository and going to through code to understand flow of it.i have knowledge of **websocket** too because i think we will need to use websocket to support collaborative mode. what else should i know to work on this project?

**Comment by ugurdogrusoz** [comment]
@sagar-shah94 A good point to start is looking at the current code and functionality. Many of the new functionality should mostly come from Cytoscape.js extensions. You should review those as well.

**Comment by MLPJ** [comment]
Hi, I'm too interested in the project. At the time I'm rich with HTML5, JavaScript and CSS. At the moment I'm going through Cytoscape.js too. So I hope to give my maximum to the project. And what other things do you propose me to get in touch with before starting the project?

**Comment by ugurdogrusoz** [comment]
@MLPJ I would look at current PathwayMapper code and potential Cytoscape extensions to use from

**Comment by MLPJ** [comment]
Thank you
