### ISSUE TITLE
Make node.js command-line tool out of oncoprint.js library

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/GSoC#27]
## Background ##

The code which generates oncoprints in the cBioPortal query page is separate from the rest of the codebase. Right now it can only be easily used in a javascript page, as we do in the cBioPortal. But it would be very useful for biologists to be able to create an oncoprint by just feeding data and configuration parameters to a command-line tool.

## Goal ## 

The goal is to use the existing oncoprint library, and the node.js javascript environment, to create a fully-featured command line tool which allows users to pass in their data (format TBD), pass in configuration parameters of how they'd like the oncoprint to look, and receive an oncoprint in SVG format.

What is already supported by the library is the ability to create an oncoprint with parameters and export an SVG. What the GSoC student would do is use this library and its API to implement a command line tool which conveniently accepts data and configuration, and makes the appropriate calls to the oncoprint.js API (and potentially minor modifications to the oncoprint library as needed) to fulfill the request.

Desired features include
- Genetic alteration tracks
![image](https://cloud.githubusercontent.com/assets/636232/22226238/a34294d2-e193-11e6-9fa9-28c1011c50d0.png)

- Heatmap tracks
![image](https://cloud.githubusercontent.com/assets/636232/22226245/b061bcba-e193-11e6-981a-187bd1984b5b.png)

- Customizable render parameters, such as the colors and shapes.

- Custom data format specification, for ease of use.

- Sorting

- Feeding in your own data, or pulling data from the cBioPortal using our REST API

The end goal of your project will be to submit it as an [NPM package](https://www.npmjs.com/).

## Approach ## 

Most of the work will be command-line UX work, in javascript, and making use of the oncoprint API.

To be clear, all of the necessary oncoprint functionality is already available via oncoprint library API commands - we are already making use of them on the cBioPortal. You will need to smartly link these API calls to the command-line input experience.

## Need skills ##

Required:
- Javascript
- Experience using command-line tools, and a sense of what is a pleasant experience
- Comfort reading javascript code (to read and understand the existing code)

Good to have, but not required:
- Experience with biological data
- Experience with the [MVC](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller) pattern (this is what is used in the oncoprint.js library)

## Possible mentors ##
@adamabeshouse

**Comment by sagar-shah94** [comment]
I am interested in this project . i would like to work on this project.i have experience in node js,express.i have already cloned a repository and going through code.what else should i know to work on this project?

**Comment by binhudakhalid** [comment]
I am a Final year engineering student pursuing my Bachelor's degree in Computer Science from University of Karachi. I love to contribute on open-source projects. I have development experience in 
C, Java, R, JavaScript and its libraries such as Node, angular and express. I am hobbyist bash script-er.

**Comment by itsmekate** [comment]
Hello! I'm interested in this issue. Currently I'll just take a look and try figuring out possible solutions. Anyway, just writing to let you know. (Sure, I have background in JavaScript, Node.js etc too)

**Comment by jajodiaraghav** [comment]
Hi there,
I would really like to spend my summers working on this idea. Apart from the requirements stated above, what else should I do in order to build a strong proposal?
Thanks

**Comment by makkBit** [comment]
Any starting pointers on how to use oncoprint.js API please? @adamabeshouse

**Comment by makkBit** [comment]
I have a question.
After the user enters the data and configs, how the created oncoprint should be displayed to the user. 
I think writing it to file in pdf, png or svg format is desired. right?
