### ISSUE TITLE
Interactive web tour

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#29]
**Background**: 

With more and more features getting into [cBioPortal](http://cbioportal.org/), it becomes a challenge for new users to fully utilize the site. Interactive web tours would be very useful to get new users started. There are many features which a large percentage of users don't know about because they lack prominence in the UI. For example, [group comparison](https://www.cbioportal.org/tutorials). Advanced users don't want the hints, so there should be some way to hide the hints.

**Goal**: 

Implement an interactive tour version of one or more of the tutorials: https://www.cbioportal.org/tutorials.

**Approach**: 

There is already some code available for that does a web tour of the group comparison feature: https://github.com/cBioPortal/cbioportal-frontend/pull/2670. We can use that and allow the user to turn it on or off. As a first stage this could be stored in `localStorage`.

- Re-enable the group comparison web tour, disabled in this PR: https://github.com/cBioPortal/cbioportal-frontend/pull/2670.
- Use `localStorage` to remember whether a user has turned on `hint` mode or not. This allows enabling/disabling the group comparison tour.
- Create another web tour for one of the tutorials here: https://www.cbioportal.org/tutorials
- Bonus: store the user state as a `setting` in the session service: https://github.com/cbioportal/session-service

**Need skills**: 

- Javascript 
- ReactJS

**Possible mentors**: 
Aaron, @leexgh, @dippindots @inodb

**Comment by aradhyamakkar97** [comment]
Hello, 
The project looks interesting. I don't have experience in developing interactive web tours although I would like to learn it for the project. I have experience in Javascript. Can I still apply for the project? Also, recipe for the tour will be given to me or I would need to prepare them myself?

**Comment by GayanSamuditha** [comment]
Hi,
I'm interesting in this project and i have experience in developing web applications, sites (interactive web tours) using boostrap and java scripts.  So i was a Biology student in school i have knowledge in biological sides and i'm very interested in this project. So can u give some information about , how i do the project what kind of i would need to prepare myself.

**Comment by jjgao** [comment]
@aradhyamakkar97 @GayanSamuditha : Thanks for you interest. Experience in JS would be useful / necessary. We will help develop the recipe of the tour.

To get started, please get familiar with cBioPortal (http://www.cbioportal.org/). You may find our tutorial paper helpful (http://www.ncbi.nlm.nih.gov/pubmed/23550210).

**Comment by GeekyShiva** [comment]
Hi @jjgao , I am highly interested in this project , though i am very much familiar in developing various web app/ extensions/ scripts in Javascript , there is still an option of developing a light weight tour of the various website component using WebGl and javascript for better and animated visualization or the website. How do you think about this idea?? I wish to discuss more about it if you like it and can be done for Gsoc 2017

**Comment by pratikabhinav** [comment]
Greetings from India @jjgao @schultzn.
I went through the several ideas listed on the _ideas_ page, and after much thought I have picked this one ( #29 Interactive web tour) to move forward with. I also have the outline/first draft of the proposal ready as per the template mentioned in the guidelines. But I am still confused as to where do I send (post) my proposal? I could not make that out from the instructions on my own.

I hope you can help clear my doubt.

Thank you.

**Comment by jjgao** [comment]
Thanks for everyone's interest. Again, a good starting point is our paper (https://www.ncbi.nlm.nih.gov/pubmed/23550210). For example, if it would be great the examples in the paper can be implemented.

**Comment by koushikAB** [comment]
Hello @jjgao  @schultzn 
I am presently studying 2nd year of my dual degree (M.Sc in biological sciences and B.tech) in BITS Pilani , India
After lots of thought and understanding every project of cBioPortal ,I consider myself capable and is very excited to do this project.
Currently i have experience in working with 2 websites and have certifications in web designing from sites like udemy 
And i am interested and looking forward to work for this project
So how can i approach/apply ....can you help , please! @jjgao , Thanks in advance!

**Comment by iFlameing** [comment]
@jjgao I would like to work on this issue :)

**Comment by rajmeghpara** [comment]
@jjgao I would also like to work on this issue.

**Comment by rajmeghpara** [comment]
Hi all, I hope you are doing fine. I am Raj Meghpara currently in final year. I have worked on ReactJS, redux and also SSR(Server Side Rendering) during my last summer internship.

Here is my github profile: https://github.com/rajmeghpara

Here is the app I have developed from scratch using ReactJS: https://elastic-fermi-485961.netlify.com/
I have also published an article for users to build it from scratch: https://medium.appbase.io/how-to-build-a-movie-search-app-with-react-and-elasticsearch-2470f202291c
I have also enabled SSR(Server side rendering). I was really able to see the difference. Kindly visit the “Bonus point” in the blog.
Here is the link to the code: https://github.com/rajmeghpara/MovieSearch-app

Here is the another app that is Airbnb Clone built from scratch using ReactJS: https://heuristic-euler-9e064d.netlify.com/
Here is the link to the article: https://medium.appbase.io/how-to-build-an-airbnb-clone-with-react-and-elasticsearch-8eb91e7e85e2
Here is the link to the code: https://github.com/rajmeghpara/Airbeds-app

I was going through the list of gsoc projects, this project interests me the most. I thought I would be able to make an impact by contributing to this project.

Can I start working on this issue?

I am excited to start the contribution.

Thanks!

**Comment by jjgao** [comment]
@iFlameing @rajmeghpara thanks for your interest. To get started, please get familiar with cbioportal.org. The tutorials (http://www.cbioportal.org/tutorials) would be helpful. Please let us know if you have any questions.

**Comment by resuls** [comment]
Hello!
I'm interested in this project for GSoC, how can I get started?

**Comment by sarru1291** [comment]
Hello cBioPortal community! I’m Sarvottam kumar pursuing B.Tech 3rd year from Bharati Vidyapeeth College of Engineering, New Delhi.

I have worked on various projects related to data-handling using AJAX, JSON, and REST API using Flask, NodeJS and also interactive UI using ReactJS. My recent work was building UI and REST API for integrated retinopathy and skin cancer web app using ML.(demo: https://retinoskin.herokuapp.com/ ). for more refer to my github ( https://github.com/sarru1291 ).

Hence, I am keenly interested and looking forward for contributing to your project ideas issues #65, 63, 58, 49, 29, 41 as i found this project interesting and also compatible to my skills. 

Kindly mentors please guide me where and how to start contributing to resolve the issues. (GSOC 19)

**Comment by LakshanSS** [comment]
Hi All! I am interested in doing this tour guide. I have worked with React and JavaScript in various projects. I am going to get started with cbioportal and try the tutorials.

**Comment by Parth910** [comment]
Hello, community!! I am Parth Patel from Jaipur, Rajasthan, India. Currently, I am pursuing my B.Tech Sophomore in Computer Science and Engineering at The LNMIIT, Jaipur.

I have Experienced in various Javascript framework like NodeJs, ReactJs and etc. I worked in a project which builds in ReactJs.So now I am interested in this issue.so please, mentors guide me how and where I can start to contribute to solving this issue.

**Comment by jjgao** [comment]
@sarru1291 @LakshanSS @Parth910 thanks for your interest. Please following [How to Apply](https://github.com/cBioPortal/GSoC/wiki/ideas#how-to-apply) to get started.

**Comment by inodb** [comment]
@alisman @jjgao should we keep this one? It seems to me that the introduction of group comparison was doing something similar. I guess if we want to do this we should maybe re-use some of that code? It might be nice to either focus on the tutorial aspect (i.e. completely new users) or make it easier to introduce new features in the same way as we did with group comparison.

**Comment by neelesh17** [comment]
Hello!! I am Neelesh Thakur from Bhopal, M.P., India. Currently, I am pursuing my B.Tech Degree in Computer Science and Engineering at The LNCTS, Bhopal.

I have Experienced in various Javascript framework like NodeJs, ReactJs, also with Redux. I worked in a project which builds in ReactJs and Redux and I am interested in this issue and also an aspirant of GSoC 2020.So mentors,would you guide me how and where I can start to contribute to solving this issue.
