### ISSUE TITLE
Continuous Integration and Deployment of cBioPortal

### ISSUE THREAD

**Issue by inodb** [cBioPortal/GSoC#30]
**Background**: 
We already have an automated test and deploy solution for the public version of cBioPortal. However deployment and testing of the internal cBioPortal used at Memorial Sloan Kettering Cancer Center is a manual process. We would like to move towards a more automated deployment more tightly integrated with GitHub. 

**Goal**: 
Automatically test and deploy the master branch of cBioPortal to our local server after new commits are pushed to the master branch of the cBioPortal repo. 

**Approach**:
There are various local integration tools one can use to set up this type of automated deployment. Jenkins might be a good candidate.

**Need skills**: 
- Basic knowledge of git and server deployment

**Possible mentors**: 
@inodb

**Comment by dracarys09** [comment]
@inodb any particular reason for choosing Jenkins ? Can we use TravisCI ?

**Comment by latifaabdullayeva** [comment]
Hi @inodb, 

I have a few questions regarding description:
 - Are there any specific requirements to the CI pipeline? For example, do you have any static analysis plugins in the toolchain? 
 - How often deployment should occur? Based on new commits or git tags?
 - What is the test environment at current stage? Do you have any end-to-end tests which require special environment configuration?

I would be happy to learn more about this project idea, but I need more details on requirements in order to be helpful. 

Thank you.

**Comment by inodb** [comment]
Hi @dracarys09 and @latifaabdullayeva! Thanks so much for your interest!

@dracarys09 

- We already use Travis CI, see: https://github.com/cbioportal/cbioportal and https://github.com/cBioPortal/cbioportal-frontend for public data. Additionally we want to use a local CI set up to test the portal with private data loaded. Also for reviewing purposes it would be nice if we could automatically deploy certain protected branches locally (i.e. our master branch can only be pushed/merged to by the admin).

@latifaabdullayeva 

- We have a few static analyses services that we use i.e. CodeClimate and CodeCov for the frontend: https://github.com/cBioPortal/cbioportal-frontend. We also already have automated deployment on Heroku. The idea of this project would mostly be to automate local deployment in a way that's easy for other people/institutions to replicate. By making this deployment process more open, we hope all can benefit
- Automatic deployment should occur for at least the master and release candidate branches on every commit. We have so far worked with the model that each merge from rc to master is tagged. It's a variation on git flow (https://datasift.github.io/gitflow/IntroducingGitFlow.html)
- Best idea of the test environment you can get from looking at the `.travis.yml` file. We don't have to run all the tests there, since those are already being run. The key issue is the local automatic deployment after all those tests passed. Ideally we could add one or two automated tests for the local deployment but it's not essential

Thanks!
