### ISSUE TITLE
Clinical Data Standardization

### ISSUE THREAD

**Issue by inodb** [cBioPortal/GSoC#31]
**Background**: 
Data in the cBioPortal is organized by studies (e.g. genomic and clinical data related to a certain publication). Recently we have made some changes that allow for more easily comparing studies' clinical data. However since a lot of that data is not standardized it is not always very easy to compare. In this project we will analyze the clinical data of various studies and see how similar/distant they are. The idea is to come up with clinical data specification(s) that will allow for more easy comparison between studies.

**Goal**: 
Propose a standard for clinical data.

**Approach**: 
Analyze the existing clinical data in cBioPortal and find out what kind of clinical data is available for most studies in the database.

**Need skills**: 
- MySQL
- Python
- Basic idea of database design

**Possible mentors**: 
@inodb, [Angelica Ochoa](https://github.com/angelicaochoa), @ritikakundra

**Comment by articuno12** [comment]
Hi @inodb. I liked your idea and would be  interested in working on this idea. I have experience with diverse databases like  MySQL , Basex and Neo4j.I have worked on several projects based on python and  have experience in designing a database for fast and proficient data retrieval. I would like to discuss on this idea further with you.

**Comment by dimuthnc** [comment]
Is this project requires some kind of biological knowledge to analyze those clinical data?

**Comment by bishal1995** [comment]
Hi @ritikakundra , I am eager to work on this project, I have designed database from e-commerce data to species data along with geographical data, please have a look on my previous work experience and ping me if I can contribute.
[BishalPaulCV.pdf](https://github.com/cBioPortal/GSoC/files/848638/BishalPaulCV.pdf)

**Comment by Parth2311** [comment]
Hi, I would like to work on this project. I have good knowledge of Database management system and I am decent coder in python. I would be glad to work on a project aimed at helping eradicate cancer from the world.

**Comment by amsonu** [comment]
Hello,I am interested to work on this project.I have good knowledge in mysql and other database systems.Please guide me through further steps.
