### ISSUE TITLE
Refactor cBioPortal frontend to use React

### ISSUE THREAD

**Issue by inodb** [cBioPortal/GSoC#32]
**Background**: 
Over the last few months we have been refactoring a lot of frontend code to use React. There are still several pages left that would benefit from using React. For instance the query page has several widgets that don't use React:

http://www.cbioportal.org/cross_cancer.do?cancer_study_list=&cancer_study_id=all&data_priority=0&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=TP53+PIK3CA&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&Action=Submit#crosscancer/overview/0/TP53%20PIK3CA/hnsc_broad%2Chnsc_jhu%2Chnsc_mdanderson_2013%2Chnsc_tcga%2Chnsc_tcga_pub

Similar for the patient view page.

Compare new:

http://cbioportal-frontend-demo.herokuapp.com/?cancer_study_id=lgg_ucsf_2014&case_id=P04

vs old:

http://www.cbioportal.org/case.do?cancer_study_id=lgg_ucsf_2014&case_id=P04

**Goal**: 
- Refactor Part of the Query Page or Patient View Page to use React

**Approach**: 
- Tackle components one by one, moving them to our new frontend repo: https://github.com/cBioPortal/cbioportal-frontend
- Choose one of three components to refactor:

    1. Genomic overview on Patient View Page (https://github.com/cBioPortal/GSoC/issues/6)
    2. Plots tab on query page:
        http://www.cbioportal.org/index.do?cancer_study_list=brca_tcga&cancer_study_id=brca_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=brca_tcga_rna_seq_v2_mrna_median_Zscores&Z_SCORE_THRESHOLD=2.0&genetic_profile_ids_PROFILE_PROTEIN_EXPRESSION=brca_tcga_rppa_Zscores&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=brca_tcga_all&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=TP53+PIK3CA&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&
    3. Mutations tab on query page:
        http://www.cbioportal.org/index.do?cancer_study_list=brca_tcga&cancer_study_id=brca_tcga&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=brca_tcga_rna_seq_v2_mrna_median_Zscores&Z_SCORE_THRESHOLD=2.0&genetic_profile_ids_PROFILE_PROTEIN_EXPRESSION=brca_tcga_rppa_Zscores&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&case_set_id=brca_tcga_all&case_ids=&patient_case_select=sample&gene_set_choice=user-defined-list&gene_list=TP53+PIK3CA&clinical_param_selection=null&tab_index=tab_visualize&Action=Submit&show_samples=false&

**Need skills**: 
- JavaScript
- Basic Knowledge of React would be useful, but not esssential

**Possible mentors**: 
@inodb @jjgao

**Comment by aradhyamakkar97** [comment]
Hello, 
I am interested in this project. I have knowledge of Javascript but I don't have experience with React (although I would like to learn it). Do you have any warmup/evaluation tasks for the project? How should I start?

**Comment by inodb** [comment]
Hi @aradhyamakkar97! Glad to hear you are interested! For starters you could try to get this project running: https://github.com/cBioPortal/cbioportal-frontend. There are several React Tutorials mentioned in the wiki: https://github.com/cBioPortal/cbioportal-frontend/wiki/Learning. Once you got the project set up and read a little bit about React we can discuss some warmup task to implement. Let me know if you have any questions!

**Comment by inodb** [comment]
@aradhyamakkar97 This might be a good issue to get started: https://github.com/cBioPortal/cbioportal-frontend/issues/160. Let me know if you have any questions!

**Comment by aradhyamakkar97** [comment]
Thanks for replying!  I have started learning from the resources you mentioned and I'll try to solve the issue as soon as possible.

**Comment by inodb** [comment]
Thanks @aradhyamakkar97!

**Comment by inodb** [comment]
Also @aradhyamakkar97 If you send me an email (x at y dot pm where x=y=ino), I can see if I can add you to our group chat, might be useful to get answers to your questions

**Comment by tessact** [comment]
Hello @inodb I am interested in collaborating on this project. I am experienced Reactjs Developer. Kindly guide me on where to start.

**Comment by apurvgandhwani** [comment]
Hello @inodb I am interested in contributing to this project. I am an experienced React developer. Kindly guide me on where to start?

**Comment by Thuva4** [comment]
Hello,
I am interested in this project. I am currently working on a react project and have experienced in Javascript. 
I have already cloned the repository and going through code.what else should i know to work on this project?

**Comment by latifaabdullayeva** [comment]
Hi @inodb, 

After building the project from the source code, I have noticed that many components which are present in the production version of the portal are not implemented yet in a new one. 

- Could you please specify which components / widgets you want to be re-written? 
- Do you have any suggestions on what is the best starting point for learning / grasping the codebase?
- Are you accepting pull-requests from non-organization contributors? If yes, do you have any specific requirements on the code style?

Thank you.

**Comment by inodb** [comment]
Hi @aradhyamakkar97, @Thuva4 , @latifaabdullayeva !

Thanks so much for your interest!

I would start with trying to run the frontend code as described in the README:

https://github.com/cBioPortal/cbioportal-frontend

Then once you got that running, you could have a look at some of the easier issues:

https://github.com/cBioPortal/cbioportal-frontend/issues?q=is%3Aopen+is%3Aissue+label%3A%22Difficulty+Novice%22

If your unfamiliar with React, it would also be good to follow a few React tutorials.

We are currently mostly working on the patient view refactoring. You can see how far we are by comparing:

http://www.cbioportal.org/case.do?cancer_study_id=lgg_ucsf_2014&case_id=P04

and

http://cbioportal-frontend-demo.herokuapp.com/?cancer_study_id=lgg_ucsf_2014&case_id=P04

Some components are simply wrapped however to work as React components but aren't fully re-implemented Those could be good components to improve, see e.g.: https://github.com/cBioPortal/GSoC/issues/6. Given the interest in this project, we'll try to outline some more components to work on in the following days.

To answer your last question @latifaabdullayeva. We definitely want to accept pull requests (PRs) from non-organization contributors. We have some lint checkers set up to help with the code style. We also review the PRs and will help you get everything in order. This frontend refactoring project is quite now, so far we've only had contributions from members of the organization.

**Comment by aditya1315** [comment]
Hi @inodb,

I ran into a few problems while building the project, could you help me out? (specifically, webpack is failing to build)

While trying to run the node server, I get the following errors, 

```
Error: ENOENT: no such file or directory, open '.env'

ERROR in /Users/aditya/Documents/github_projects/cbioportal-frontend/typings/globals/lodash/index.d.ts
(22713,11): error TS2428: All declarations of 'WeakMap' must have identical type parameters.

ERROR in ./src/pages/datasetView/DatasetList.tsx
(56,9): error TS2532: Object is possibly 'undefined'.

```
I tried to clean the cache and re-run this, but without any success. In the webpack config file, I made the silent: false for the environmentEnv variable. Any help is appreciated.

**Comment by aradhyamakkar97** [comment]
@aditya1315 use mobx branch. It worked for me.

**Comment by aditya1315** [comment]
@aradhyamakkar97 this error still persists in mobx branch also

**Comment by inodb** [comment]
Thanks so much for your interest all! Best is to use integration branch now.

**Comment by vchilkuri** [comment]
Hello @inodb , I am Venkata Chilkuri. I am a graduate student at IUPUI and I do have experience with Javascript and ReactJS. I have created a single page application using react-router where a form was created to get observations from multiple JSON files using API calls. I am very interested in this project and would like to contribute to this project. Does this project use only react or any other addons like redux etc.
