### ISSUE TITLE
Support mRNA expression from normal samples

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#33]
**Background**: 

In the [cBioPortal](http://cbioportal.org), gene expression data can be used for many analysis, including: OncoPrint, Plot tab correlation, cross cancer expression, etc. See [our Sci. Signal. paper](https://www.ncbi.nlm.nih.gov/pubmed/23550210) for details. A frequently asked feature is to integrate expression data from normal sample into these analyses.

**Goal**: 

- Import normal expression data into our database
- Support z-scores calculating with normal expression data
- Use normal data in Plots tab, e.g. in plots of mRNA vs CNA, add another category of normal data
- Use normal data in the cross cancer expression plots

**Approach**: 

- TCGA normal data can be used, see [Broad Firehose](http://gdac.broadinstitute.org/) expression data for example normal data
- (optional) use GTEx normal data
- Load normal data into database as a genetic profile
- Z-scores needs to be calculated in the frontend

**Need skills**: 

Java, Javascript

**Possible mentors**:

**Comment by kapilkd13** [comment]
Hi 
I would like to work on this project. Right now i am deploying cBioPortal on my local machine. Is there a implementation of z-score Algorithm. If yes, it would be great if you can point me to it.

**Comment by smoke10** [comment]
Hello Sir,
 I am interested in this project. I am a beginner at GITHUB  please guide me how to contribute to the project . I am good at JAVA programming  and algorithms . I need your help . Thanks.

**Comment by cptnjk** [comment]
Hi
I am good at JAVA and would like to work on this project, can you please guide me as to how to get started, thanks.

**Comment by n1zea144** [comment]
@kapilkd13 You can find the library for calculating z-scores in this js file:

[cbio-stat.js](https://github.com/cBioPortal/cbioportal/blob/master/portal/src/main/webapp/js/src/cbio-stat.js).

Note, the denominator would change if tcga normal samples were included (or GTEx data).  I think one approach would allow the user to choose the reference cohort.

**Comment by shehan1993** [comment]
Hello sir,
I am shehan,

According to my understand this project is gene data analyzing project (correct me ).
Please give some extra reference read about this project or related to this kind of project.

**Comment by evoxtorm** [comment]
Hey this project is selected for gsoc 2017 or not.
