### ISSUE TITLE
Update R API

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/GSoC#37]
**Background**: would be good to update current R API of cBioPortal according to the latest web API as found in http://www.cbioportal.org/api . Furthermore, it would be good to document ways to easily integrate this with current authentication and authorization methods supported by cBioPortal.

**Goal**: updated R API that can be easily updated again when new additions are made to the web API.

**Approach**: 
- develop a script to automatically generate as much as possible of the API code from the Swagger configurations. Make custom improvements where this is not possible or where the resulting API is too slow or hard to use. 
- when the API is ready, run and document some real data analysis in R using the new R API. 
- also develop an integration tests where some well-known TCGA results are reproduced using the new R API. 

**Needed skills**: 
- understanding of Swagger and REST APIs
- good R skills 
- bioinformatics knowledge to test the API and develop the tests mentioned above

**Possible mentors**: 
- @pieterlukasse (co-mentor)
-

**Comment by ersinciftci** [comment]
@pieterlukasse https://github.com/swagger-api/swagger-codegen claims they have an R client generator now, not sure if it works.

**Comment by inodb** [comment]
@ersinciftci @pieterlukasse I have used it a bit for genome nexus, seems to work: https://github.com/genome-nexus/genome-nexus/blob/rc/notebooks/genome_nexus_r_example.ipynb. More detailed example also connecting to cBioPortal API here: https://github.com/genome-nexus/genome-nexus/blob/rc/notebooks/genome_nexus_python_example.ipynb

**Comment by pieterlukasse** [comment]
@inodb @ersinciftci thanks for the feedback. Do you think this topic is still GSOC worthy or is it too simple now?
