### ISSUE TITLE
Improving PathwayMapper for collaborative construction of cancer pathways

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/GSoC#39]
**Background**: 
While the network visualization module in cBioPortal is a powerful exploration tool, most biologists are more comfortable with the kind of simplified, curated pathway diagrams that are featured in many manuscripts from The Cancer Genome Atlas (TCGA) . With the motivation of creating a platform that provides more intuitive pathway diagrams, yet supports these with rich data ‘decoration’ and analysis with access to data in cBioPortal, with attractive visualization, we developed a tool named [PathwayMapper](https://github.com/iVis-at-Bilkent/pathway-mapper) [1].

**Goal**: 
The goal of this project is to implement new exciting features for a new version of PathwayMapper including:
- expand-collapse, hide-show operations for complexity management
- filtering (by alteration percentage) and highlighting capabilities
- edge bends
- chat support for the collaborative mode
- undo support for the collaborative mode

[1] I. Bahceci, U. Dogrusoz, K.C. La, Ö. Babur, J. Gao, N. Schultz, "PathwayMapper: a collaborative visual web editor for cancer pathways and genomic data", Bioinformatics, 33(14), pp. 2238-2240, 2017.

**Approach**: 
PathwayMapper is based on [Cytoscape.js](http://js.cytoscape.org). We will try to reuse the extensions available for Cytoscape.js.

**Need skills**: 
Good programming skills is required. Experience in web technologies (JavaScript, html, css) and/or visualization software is a plus.

**Possible mentors**: 
[Ugur Dogrusoz](https://github.com/ugurdogrusoz)

**Comment by kunal-mohta** [comment]
Hello @ugurdogrusoz 
I have experience in HTML, CSS and JavaScript, and am currently learning Node.js.
What can be my initial steps to contribute to this project?

**Comment by ugurdogrusoz** [comment]
@kunal-mohta You could investigate current PathwayMapper implementation (read the paper and review the related GitHub repository) in detail to start with. You also need to learn Cytoscape.js and extensions of Cytoscape.js that we use in PathwayMapper project.

**Comment by kunal-mohta** [comment]
@ugurdogrusoz Thank you for replying.
I will start with reading of the PathwayMapper paper and repository and will get to know about Cytoscape.js.
