### ISSUE TITLE
React Component Scatter Plot

### ISSUE THREAD

**Issue by inodb** [cBioPortal/GSoC#46]
**Background**: 
[cBioPortal](https://github.com/cbioportal/cbioportal) has various scatter plots throughout the website. See e.g.: http://www.cbioportal.org/study?id=msk_impact_2017#summary. We would like to be able to support multiple panels and correlation lines. We've been looking at [Victory Charts](https://formidable.com/open-source/victory/docs/victory-scatter/#groupcomponent). It might be worthwhile extending that library to suit our needs. Some examples of scatter plot functionality that's still missing: https://www.r-bloggers.com/scatterplot-matrices/, https://python-graph-gallery.com/40-basic-scatterplot-seaborn/. 

**Goal**: 
- Create a Scatter plot component for use in the [cBioPortal frontend](https://github.com/cBioPortal/cbioportal-frontend). 
- We would like:
    1. correlation lines
    2. correlation matrices
    3. kernel density estimation
    4. handle >100K points

**Approach**: 
Investigate existing scatter plot libraries that could support our use case. Compare SVG and Canvas performance. Perhaps extend [Victory Charts](https://formidable.com/open-source/victory/) to fit our needs. 

**Need skills**: 
JavaScript, React

**Possible mentors**: 
@inodb 

**Chat with us**: 
[![Join the chat at https://gitter.im/cBioPortal/public-chat](https://badges.gitter.im/cBioPortal/public-chat.svg)](https://gitter.im/cBioPortal/public-chat?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by jjgao** [comment]
I don't think we need this anymore with the density plot.
