### ISSUE TITLE
Swimmer's Plot and Waterfall Plot for Treatment Analysis

### ISSUE THREAD

**Issue by inodb** [cBioPortal/GSoC#48]
**Background**: 
We are expanding [cBioPortal](www.cbioportal.org) to allow for better analysis of treatment and response information.  Two visualizations would be incredibly useful:  
- A swimmer plot is a common visualization for showing patient response information. See for example: https://peltiertech.com/swimmer-plots-excel/. 
- Another common visualization is the waterfall plot, see e.g.: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4093310/.

**Goal**: 
Create Two React Components: swimmer plot and waterfall plot.

**Approach**: 
In the [cBioPortal frontend](https://github.com/cBioPortal/cbioportal-frontend) we use React. We would like to create two new components for these charts. Ideally using or extending [victory charts](https://formidable.com/open-source/victory/docs/victory-chart/). User should be able to render the bars based on different sample/patient attribute.

**Need skills**: 
JavaScript, React (can be learned during the program)

**Possible mentors**: 
@inodb 

**Chat with us**: 
[![Join the chat at https://gitter.im/cBioPortal/public-chat](https://badges.gitter.im/cBioPortal/public-chat.svg)](https://gitter.im/cBioPortal/public-chat?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by sandertan** [comment]
RFC for the project Sjoerd mentions: https://docs.google.com/document/d/1jbpnWjlVxEpigFkNhr9LzhZ0rmUy9WleYa_neUSV4Js/edit

**Comment by inodb** [comment]
Thanks @Sjoerd-van-Hagen and @sandertan! I'll close this for now then
