### ISSUE TITLE
Separating the Network View as a standalone module

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/GSoC#49]
**Background**: 
The network visualization module in cBioPortal is a powerful exploration tool with data coming from [Pathway Commons](http://www.pathwaycommons.org/). However, this module's interaction with the rest of the portal components is not properly done, often resulting in conflicts in third party libraries or resources not located properly.

**Goal**: 
The aim of this project is to package the existing network view module properly so that third party libraries used by the module do not conflict with the portal with a clear interface between the module and the portal. In other words, it's nicely isolated from the rest of the portal.

**Approach**: 
There might be various ways of achieving this, one being converting the module to a proper [React](https://reactjs.org/) library.

**Need skills**: 
Strong web programming skills are required.

**Possible mentors**: 
[Ugur Dogrusoz](https://github.com/ugurdogrusoz)
[S.Onur Sumer](https://github.com/onursumer)

**Comment by r614** [comment]
Hi!

I am a Biomedical Engineering Undergrad, specializing in Bioinformatics at the University of British Columbia! I am interested in working on this project for the GSOC 2019. I was wondering if you could point me to the existing implementation in the repo and if you have any existing documentations about it. It would be really helpful for my proposal!

Thanks!

**Comment by ugurdogrusoz** [comment]
@r614 cBioPortal code base is [here](https://github.com/cBioPortal/). You might want to get familiar with the portal first by looking at [these tutorials](https://www.cbioportal.org/tutorials).

**Comment by r614** [comment]
@ugurdogrusoz Thank you for the resources! I will make sure to look through them. Is this thread okay for any further questions I have, or should I email you?

**Comment by ugurdogrusoz** [comment]
Either way is fine

**Comment by pallavi75** [comment]
Hi
I am interested to work on this project for the google summer of code 2019. I am working on free and open source technologies . I know the techstack of  java ,javascript ,database and the  basics of reactjs . . Can you provide me some information about the project in detail which helps me to contribute in gsoc.

**Comment by ugurdogrusoz** [comment]
@pallavi75 see comments above please
