### ISSUE TITLE
Support more protein annotations in MutationMapper and GenomeNexus

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#5]
**Background**: MutationMapper is a Javascript library for visualization of mutations in the context of protein annotation. MutationMapper connects to Genome Nexus which is a resource to provide annotation for mutations. Currently MutationMapper visualizes PFAM domain and 3D structures.

![image](https://cloud.githubusercontent.com/assets/840895/12772284/eebd7e3a-c9fd-11e5-9601-5a43928e3ef5.png)

**Goal**: Supports more protein annotations such as protein post-translational modifications (PTM), protein motifs, dna binding, secondary structures, etc.

**Approach**:
- Build a pipeline to retrieve annotation from sources such UniProt, PhosphoSitePlus, Emsembl, and RefSeq.
- Model annotation data in Genome Nexus database.
- Provide annotation data through Genome Nexus web API.
- Visualization of annotation in MutationMapper.

**Need skills**: Java, Javascript, Web API.

**Possible mentors**: [Onur Sumer](https://github.com/onursumer), [Benjamin Gross](https://github.com/n1zea144), [JJ Gao](https://github.com/jjgao),  [Angelica Ochoa](https://github.com/angelicaochoa), [Ino de Bruijn](https://github.com/inodb)

**Comment by jjgao** [comment]
EBI/UniProt just released their [protein features viewer]( http://www.ebi.ac.uk/about/news/service-news/new-view-proteins) as a [BioJS project](http://ebi-uniprot.github.io/biojs-vis-proteinFeaturesViewer/developerGuide.html). It can be potentially very useful for the visualization part of this project.

**Comment by zulrich91** [comment]
Greetings I am good in java and have worked on quiet a number of projects with Java using technologies like hibernate, javafx, spring, and apache velocity, I have some javascript knowledge and I am a guy who is always ready to learn new technologies if need be to solve a programming problem. 

I need documentations that I can follow to get acquainted with the technologies involved in this project and also i need the link to the code base to have a taste of what it looks like. 

Thanks

**Comment by AkashSevana** [comment]
Hi,
I am a 3rd year Computer Science student from GITAM University, India. I am very much interested in contributing towards this project. 
As far as I understood the MutationMapper is a library used for visualization and Genome Nexus is a package which holds a collection of Genome related information. Now the task is to retrieve more information from other sources and dump it into Genome Nexus in a structured format and then use it for visualization. 
(p.s: correct me if I am wrong!)

I would like to get started working on it. For that can someone please enlighten me with how to proceed, what steps to follow and, also it would be great if i could get some reference.

**Comment by PratyushTalreja** [comment]
Hi

I am pursuing Masters from Indian Institute of Technology Bombay. I had completed Bachelors in Information Technology. I am having a work experience of 1 year working with Cognizant Technology Solutions in Java domain. Also, I have the experience of JavaScript and Web API. I have successfully completed my GSoC 2016 project. I am interested in this project. Can you please tell me the further steps for this project.

**Comment by PratyushTalreja** [comment]
Hi

I am pursuing Masters from Indian Institute of Technology Bombay. I had completed Bachelors in Information Technology. I am having a work experience of 1 year working with Cognizant Technology Solutions in Java domain. Also, I have the experience of JavaScript and Web API. I have successfully completed my GSoC 2016 project. I am interested in this project. Can you please tell me the further steps for this project.

**Comment by jjgao** [comment]
Hi PratyushTalreja,

Thank you for your interest. We may want to work with the PDB group on their viewer (https://github.com/rcsb/proteinfeatureview). It would be useful to get familiar with that.

**Comment by mzeng29** [comment]
Hello,

My name is Jane and I am interested in this project. I am preparing proposal for this project now. And I have few questions related to implementing the tasks. Where can I find the model annotation data in Genome Nexus database? As it is mentioned above, Genome Nexus Web API needs to provide annotation data. Will Genome Nexus be a website available online?  I appreciate your help. 

Thanks.
Jane

**Comment by pieterlukasse** [comment]
hi @jjgao, for the visualization part I would like to propose Protter: http://wlab.ethz.ch/protter/start/
It is open source (GPL 3) https://github.com/ulo/Protter

**Comment by jjgao** [comment]
@mzeng29 thanks for you interest. You can find the current genome nexus api here: http://annotation.genomenexus.org/swagger-ui.html

**Comment by pieterlukasse** [comment]
The Uniprot view, for reference:
<img width="826" alt="screen shot 2019-01-21 at 17 35 28" src="https://user-images.githubusercontent.com/2900303/51487231-16266300-1da3-11e9-81b6-ca57daab6d3c.png">
