### ISSUE TITLE
Evolutionary analysis

### ISSUE THREAD

**Issue by inodb** [cBioPortal/GSoC#53]
**Background**: 

**Goal**: 

**Approach**: 

**Need skills**: 

**Possible mentors**:

**Comment by fongcj** [comment]
I was thinking of a similar idea to this, where a simple evolutionary view of alterations from multiple samples of a patient be displayed.  

![evolution__232](https://user-images.githubusercontent.com/25805540/51703243-ddc19780-1fe3-11e9-9651-e981bcd0d9b5.png)
Above is a prototype of a tree using the networkx package in python

[PhyloTree_egc036_20180308_v9.pdf](https://github.com/cBioPortal/GSoC/files/2793226/PhyloTree_egc036_20180308_v9.pdf)
This is a sketch made in Adobe illustrator, but the idea would be that the prototype version can be transformed into something like this. 

Then possibly have a hover over feature on the alterations to summarize annotations (OncoKB, hotspots, etc.)

**Comment by fongcj** [comment]
@inodb Based on prototype now, there would be 3 inputs: mutation maf and CNA calls, and lastly, a dictionary of the patient's sample IDs and relative time points (0,1,2.. etc. or dates)
The script I have now will output two tables: 
<img width="1309" alt="screen shot 2019-01-24 at 6 23 10 pm" src="https://user-images.githubusercontent.com/25805540/51715060-45d4a580-2005-11e9-8ec8-0aaca37d9432.png">
A pivot table of all gene variants against samples affected, with the (relative) time points provided

<img width="1089" alt="screen shot 2019-01-24 at 6 23 33 pm" src="https://user-images.githubusercontent.com/25805540/51715158-95b36c80-2005-11e9-8460-eb7a1272ff25.png">
And a table of computed Jaccard distances based on time points and evolution.


For the second question, maybe the user can select which samples and alteration type they want to exclude (Mutations/Amp/Dels).  I'm not sure about integration, but a wrapper could be used around my script for on the fly implementation.

**Comment by jjgao** [comment]
This looks great! It is exactly what we need.

**Comment by jjgao** [comment]
Closing this one. We will create another one once @fongcj is back.
