### ISSUE TITLE
Download files for a virtual study

### ISSUE THREAD

**Issue by inodb** [cBioPortal/GSoC#54]
**Background**:
[cBioPortal](http://www.cbioportal.org/) is a visualization platform for analyzing genomics data. The public cBioPortal data files are organized per study and available for download on [datahub](https://github.com/cBioPortal/datahub/). However, for virtual studies made by the user, there is currently no option to download the files. Tutorial 4 shows how to make a virtual study: http://www.cbioportal.org/tutorials. 

**Goal**: 
Provide an option to download data files for virtual studies. All clinical and genomics data should be included in a zip/gz file. The file format should follow [this](https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats), which is the same formats as the files in datahub.

Note: this may create a lot of load for the backend server. How can we handle that?

**Approach**: 
* Develop an API to return all genomic and clinical data in a zip/gz file based on a study or virtual study ID.

**Need skills**: 
Java, Database, SQL

**Possible mentors**:

**Comment by TechTweety17** [comment]
Hi Sir. I am interested in this project. It would be really helpful if you could please give me a brief idea about the submission of proposal and format for proposal.

**Comment by anoob09** [comment]
Heii @inodb . I am interested to work on this issue. I had a small doubt. Do we need to import all the data mentioned in  [cbioportal/docs/Import-the-Seed-Database.md](https://github.com/cBioPortal/cbioportal/blob/master/docs/Import-the-Seed-Database.md#importing-the-seed-database) to work on this issue?

**Comment by anoob09** [comment]
@jjgao @inodb [Here](http://www.cbioportal.org/datasets) is an option to data. Where can I find the genomic and clinical data that I have to return?

**Comment by kalletlak** [comment]
> Heii @inodb . I am interested to work on this issue. I had a small doubt. Do we need to import all the data mentioned in [cbioportal/docs/Import-the-Seed-Database.md](https://github.com/cBioPortal/cbioportal/blob/master/docs/Import-the-Seed-Database.md#importing-the-seed-database) to work on this issue?

@anoob09 this is just the reference data. And all the studies are present at https://github.com/cBioPortal/datahub/tree/master/public. To work on this issue, you need reference data and may be couple studies from `public` folder.


> @jjgao @inodb [Here](http://www.cbioportal.org/datasets) is an option to data. Where can I find the genomic and clinical data that I have to return?

You need to query database

**Comment by inodb** [comment]
@kalletlak Do you think this is a reasonable project for GSoC2020?
