### ISSUE TITLE
Genome Nexus Command Line Client

### ISSUE THREAD

**Issue by inodb** [cBioPortal/GSoC#56]
**Background**: 
Genome Nexus is a web service that gives information about any given change in the DNA, also known as a variant or mutation. It is an aggregation service that combines variant information from multiple sources and exposes that information through a REST API. Aside from the REST API we also provide a command line interface which allows one to annotate a file with variants (https://github.com/genome-nexus/genome-nexus-annotation-pipeline). The current implementation is quite slow and only annotates a single variant at a time using GET requests. We would like to improve this. The current implementation is written in Java and you are welcome to improve this. It would also be fine to start fresh using Python or Node.

The input format is like this: https://github.com/genome-nexus/genome-nexus-annotation-pipeline/blob/master/test/data/minimal_example.in.txt.

And output should be like: https://github.com/genome-nexus/genome-nexus-annotation-pipeline/blob/master/test/data/minimal_example.out.uniprot.txt

**Goal**: 
Improve the performance of the command line client of Genome Nexus.

**Approach**: 
Either improve current implementation or start fresh in Python or Node.

**Need skills**: 
Java, Python or Node
 
**Possible mentors**:
Onur, Ino

**Comment by thobhanifreddy** [comment]
Hello Sir, I am Freddy Thobhani, currently I am pursuing my bachelors in computer engineering(3rd year). 
I have worked on multiple nodeJS projects and would love to work on this project(can start tomorrow itself!). 
I can even work on python, but I would suggest Node.js + Express.js would be perfect for this. 

Very excited to work on this project.

**Comment by JaiKotia** [comment]
Hey, I find this project intriguing and believe I can present a refined client for the Genome Nexus service using NodeJS. I have prior experience in Node as well as Python, but a Node solution would be more sophisticated. I would like connect with a mentor and discuss the features required for this implementation. Thank you.

**Comment by rihbyne** [comment]
@inodb would like to work on this issue. Porting the existing java client to python/node and then improvising is what I can think of now.

**Comment by inodb** [comment]
Gonna close this, the NodeJS command line client is working pretty ok already: https://github.com/genome-nexus/genome-nexus-cli. We could open a new idea that fixes some small issues
