### ISSUE TITLE
Genome Nexus Variant Page

### ISSUE THREAD

**Issue by inodb** [cBioPortal/GSoC#58]
**Background**: 
Genome Nexus is a web service that gives information about any given change in the DNA, also known as a variant or mutation. It is an aggregation service that combines variant information from multiple sources and exposes that information through a REST API. For this project we would like to make a variant page that shows all the information we have about a particular variant. This is an example response with all information currently in Genome Nexus: 

https://www.genomenexus.org/annotation/genomic/7,140453136,140453136,A,T?fields=hotspots,mutation_assessor,annotation_summary

The page should list the variant name at the top of the page i.e. `7,140453136,140453136,A,T`. Then we could reuse a common visualization from cBioPortal, the mutation mapper, to show where on the protein the variant occurs:

<img width="1142" alt="screen shot 2019-01-31 at 11 33 27 am" src="https://user-images.githubusercontent.com/1334004/52069119-16b1bd00-254c-11e9-8612-645ad12746c4.png">

In the example a lot of different variants are shown from the Pan Lung Cancer TCGA study. It should be possible to switch to other data sets, so one can easily see how often that variant occurs compared to other data sets. 

Another visualization that would be useful is how often that variant occurs across cancer types:

<img width="423" alt="screen shot 2019-01-31 at 11 37 55 am" src="https://user-images.githubusercontent.com/1334004/52069451-bbcc9580-254c-11e9-9d11-d3b006e7c7cf.png">

**Goal**: 
Create a variant page for Genome Nexus that shows all the information available in the API

**Approach**: 
Use JavaScript, React and the Genome Nexus REST API to create the variant page.

**Need skills**: 
- JavaScript
- React

**Possible mentors**: 
Onur, Ino

**Comment by pieterlukasse** [comment]
page, like in UI? So it won't be just an API anymore?

**Comment by inodb** [comment]
@pieterlukasse 	exactly. Thinking about showing the lollipop plot and all the different annotations we have for a particular variant.

**Comment by lohani2280** [comment]
Hello Mentors,
I am a Final Year Undergraduate student, from India, currently pursuing my Bachelors in the Department of Information Technology. 

I have a considerable experience on working with  Javascript  and REST APIs. I have also contributed to many open source projects before, one of them being [GraphSpace](http://graphspace.org/) which is a web-based platform for storing, interacting, sharing networks and has a comprehensive REST API that allows users to communicate programmatically with it.

I find this project very interesting and wish to work on for GSoC'19. Please guide me on how to get started.

**Comment by inodb** [comment]
@leexgh I'm going to close this unless you have some specific ideas what a GSoC student could work on. Maybe mobile version of the site?

**Comment by leexgh** [comment]
@inodb good idea! that would be super cool! I'm thinking maybe the MAF annotation or patient report that we first proposed to genome nexus website could be possible projects as well?
