### ISSUE TITLE
Improved genome overview of copy number and mutation in patient view page

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#6]
**Background**: The [patient view page of cBioPortal](http://www.cbioportal.org/case.do?cancer_study_id=ucec_tcga_pub&case_id=TCGA-BK-A0CC) shows demographic and clinical information as well as an overview of genomic changes in the patient's DNA samples. At the bottom, two tables are shown with more detailed information of those genomic changes:
1. mutations, small changes to the bases of the DNA and
2. copy number aberrations, deletions or amplifications of stretches of DNA

We would like to improve the genomic overview section of the patient view page which displays mutations and copy number changes along the entire genome:

![image](https://cloud.githubusercontent.com/assets/840895/12772536/f73335c6-c9ff-11e5-92e6-10e9b269f91d.png)

The [Visual Information Seeking Mantra](http://www.ifp.illinois.edu/nabhcs/abstracts/shneiderman.html) is:

_Overview first, zoom and filter, then details-on-demand_

In our case both the overview and details part are accounted for, but the zoom and filter part is missing.

**Goal**: Improve the mini-genome browser.

**Approach**: 
- Using [igv.js](http://igv.org/doc/doc.html)
- Support zooming.
- Support probe level copy number data.
- Display only a subset of samples instead of all samples (filter)

**Need skills**: Javascript

**Possible mentors**:
@inodb @JiaoJiao123

**Comment by rohangoel96** [comment]
Hi @jjgao and @inodb , I would like to explore more about this project and also work on it in GSoC '16. How should I start?

**Comment by jjgao** [comment]
@rohangoel96 you could try to understand the current [jsp](https://github.com/cBioPortal/cbioportal/blob/rc/portal/src/main/webapp/WEB-INF/jsp/patient_view/summary.jsp) and [js](https://github.com/cBioPortal/cbioportal/blob/master/portal/src/main/webapp/js/src/patient-view/genomic-overview.js) code. You could do some debugging. 

You could also try to isolate the code into a separate standalone project. For example, for [this sample](https://github.com/cBioPortal/cbioportal/blob/rc/portal/src/main/webapp/js/src/patient-view/genomic-overview.js), here is the cna data (http://www.cbioportal.org/cna.json?cmd=get_segment&sample_id=TCGA-BK-A0CC-01&cancer_study_id=ucec_tcga_pub).

**Comment by linghong** [comment]
Hi, @jjgao and @inodb ,

I  submitted the proposal draft this afternoon. Is it possible either of you could do a quick review and give some comments, so I can make a revision before the tomorrow deadline? Sorry for giving such a short period of review time. I just got to know the Google Summer of Code 2016 two days ago.  Thank you.

**Comment by inodb** [comment]
@linghong I made some comments. I think it would be good to look at the code as in @jjgao's previous comment. Overall it's fine, but more specific implementation details would be good.

**Comment by linghong** [comment]
@inodb Thank you so much for your comments. I am working on the revision now.

**Comment by sandeepm96** [comment]
Hello Sir! I am very interested in working on this project for GSoC. Since I am new to the community I require your guidance on this. For getting started, I have cloned this repository https://github.com/cBioPortal/cbioportal and deploying the code on my local server.

**Comment by sandeepm96** [comment]
@inodb @jjgao It would be really great if a slack/gitter channel could be setup for further discussions on GSoC project ideas. :)

**Comment by inodb** [comment]
Hi @sandeepm96! Thanks for your interest in this project! I sent you an invite to the slack channel.

Please also try to get the new cbioportal frontend repo running: https://github.com/cBioPortal/cbioportal-frontend. We have been iteratively replacing components of the old site with new React components. This component will be developed in the new frontend.

**Comment by sandeepm96** [comment]
Thank you @inodb sir.
I got to know about the new frontend repository a little later. I have made it run and trying to understand the codebase now. I will try solving issues soon. :)

**Comment by palset** [comment]
Hi, I am interested in this project. I realise I am a bit late, and have cloned the cbioportal repository and the cbio-frontend repo. How do I proceed? :)

**Comment by Ishu-Kalra** [comment]
Hi, I am looking into this.
