### ISSUE TITLE
Human Genome Variant Society format converter

### ISSUE THREAD

**Issue by inodb** [cBioPortal/GSoC#60]
**Background**: 
A commonly used representation of genomic variants is the Human Genome Variation Society  format. The spec is provided here: http://varnomen.hgvs.org/. We would like to be able to convert that to other common formats such as [Variant Call Format](https://samtools.github.io/hts-specs/VCFv4.2.pdf) and [Mutation Annotation Format](https://software.broadinstitute.org/software/igv/MutationAnnotationFormat) and vice versa.

[Genome Nexus](https://github.com/genome-nexus/genome-nexus/) is a web service that aggregates variant information from multiple other web services. To be able to communicate between these different services it is essential to be able to switch between multiple variant representations easily. The format converter will be implemented in this project, but could be beneficial to many other genomics projects. The solution should be general enough, perhaps using regular expressions, so it can be reused in other languages.

**Goal**: 
Implement a converter that can parse HGVS, VCF and MAF and output in any of those formats. 

**Approach**:
Follow the spec here http://varnomen.hgvs.org/ to come up with a set of rules for parsing HGVS. Ideally these rules should be easily portable to another language. E.g. using regular expressions.

The HGVS format is a way to represent variants in a single string without spaces. MAF and VCF are both tab delimited formats. There is no filetype HGVS. Only MAF and VCF are file formats.

In MAF the format to represent a variant is like this:

https://github.com/genome-nexus/genome-nexus-annotation-pipeline/blob/master/test/data/minimal_example.in.txt

For VCF it is:

https://github.com/inodb/sufam/blob/master/example/sufam.vcf

HGVSg is e.g.:

17:g.41242962_41242963insGA

**Need skills**: 
Java

**Possible mentors**: 
inodb, onursumer, @ao508

**Comment by css911** [comment]
hello....  @inodb the idea seems interesting to me. Where i should proceed in order to understand the problem statement better?

**Comment by Oguzyildirim** [comment]
hello, i am so happy because  in my university we have Bioinformatics Masters Program and i want to apply for it. Working on this project will be so much valuable to me. So can we use here to ask question after reading links?

**Comment by inodb** [comment]
@css911 @Oguzyildirim Thanks for your interest! https://slack.cbioportal.org is a good place to ask for questions

**Comment by Alhena26** [comment]
Hello ! Can I know to whom I should send my first draft for a proposal to ? 
Thank you

**Comment by ao508** [comment]
Hi @alhena26. You should request an invite to the cbioprtal gsoc slack group and share a link there.

**Comment by Alhena26** [comment]
I am already on slack.
Do you suggest I put my proposition on github and then send the link on
slack's GSOC channel ? But then it will be visible for everyone ?

**Comment by ao508** [comment]
hi @Alhena26 , you can start a private conversation on Slack with myself, @inodb and @onursumer if you wish. You can share a google doc with your proposal

**Comment by Alhena26** [comment]
Hello @ao508 ! I just added @inodb  and @inodb to the conversation, but I can't find you on slack !

**Comment by ao508** [comment]
@Alhena26 you should be able to find me under my name (Angelica)

**Comment by Alhena26** [comment]
I just added you ! :)

Le 5 avr. 2019 5:02 PM, "ao508" <notifications@github.com> a écrit :

@Alhena26 <https://github.com/Alhena26> you should be able to find me under
my name (Angelica)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cBioPortal/GSoC/issues/60#issuecomment-480309258>, or mute
the thread

**Comment by Alhena26** [comment]
Hello ! Thank you @ao508 for you feedback ! I've made some modifications based on your suggestions, and submitted another draft. Can you give me your thoughts on this new proposal ?
