### ISSUE TITLE
Embed Aligned Reads in Patient view with IGV

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/GSoC#62]
**Background**: 
Alignments are very useful when deciding if a mutation is real. Seeing the surrounding reads can help users determine whether the alignments are clean. For example, lots of other mutations in the surrounding reads could indicate alignment ambiguity.

**Goal**: 
Make the raw alignments available in mutation and copy number alteration tables from the patient view.

**Approach**: 
For each mutation, an IGV icon when clicked brings the user to a small window surrounding the mutation where the user can see the reads.

**Skills Needed**: 
Java, React JS, Babel, SCSS

**Possible mentors**: 
khzhu, tjpugh

**Comment by sohnsteve** [comment]
Hello, I am interested in undertaking this project but am worried how hard of a requirement there is for knowing the skills you have listed.  For instance, I have been coding in Java for practically my entire academic career so far and so I feel confident on that front, but have only dabbled in JS and CSS.  Of course, it goes without saying that I will learn whatever skills I am required of, but will that be good enough?

**Comment by khzhu** [comment]
@sohnsteve , thank you for your interest in the project! 
The project is mainly developing a new **React** module for the cBioPortal GUI component. Of course, you can pick up new skills as you go. To get yourself familiar with type script, especially to have a basic knowledge of the babel transpiler and React Promise will help you find a good design solution faster.

**Comment by adamabeshouse** [comment]
I think this project is way too small for an entire summer. It is basically creating a single button which links to a single location in the igv window which is already implemented.

**Comment by khzhu** [comment]
@adamabeshouse , currently we can only view segments in the portal not raw reads from bam, right?

**Comment by adamabeshouse** [comment]
@khzhu oh yes, you're right

**Comment by jjgao** [comment]
The authentication part to load slide of bam is probably the main work.
