### ISSUE TITLE
Swimmer's Plot and Waterfall Plot for Treatment Response Data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#63]
**Background**: 
We are expanding [cBioPortal](www.cbioportal.org) to allow for better analysis of treatment and response information. Two visualizations would be incredibly useful:  
- A swimmer plot is a common visualization for showing patient response information. See for example: https://peltiertech.com/swimmer-plots-excel/. 
![image](https://user-images.githubusercontent.com/840895/53600651-10792580-3b78-11e9-9ac0-7c292cd178d3.png)

- Another common visualization is the waterfall plot, see e.g.: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4093310/.
![image](https://user-images.githubusercontent.com/840895/53600668-1a9b2400-3b78-11e9-836a-cfb914681095.png)

There is currently a [pull request](https://github.com/cBioPortal/cbioportal-frontend/pull/2055) to implement the waterfall plot. The only missing part is coloring the bars with clinical data.

**Goal**: 
* Create a REACT component for waterfall plot.
* Enhancing swimmer plot (as implemented [here]((https://github.com/cBioPortal/cbioportal-frontend/pull/2055)))
* Integrate them into [Plots tab](http://bit.ly/2VmWmkI)
* Allow coloring the bars with clinical data

**Approach**: 
In the [cBioPortal frontend](https://github.com/cBioPortal/cbioportal-frontend) we use React. We would like to create two new components for these charts. Ideally using or extending [victory charts](https://formidable.com/open-source/victory/docs/victory-chart/). User should be able to render the bars based on different sample/patient attribute.

**Need skills**: 
JavaScript, React (can be learned during the program)

**Possible mentors**:
@Luke-Sikina

**Comment by coderrsid** [comment]
Hey @jjgao I want to work on this issue and issue #65 for GSOC. How do i get started?

**Comment by jjgao** [comment]
Hi @coderrsid, thanks for your interest! 

If you are not familiar with [cBioPortal](https://www.cbioportal.org), learning cBioPortal might be the first step. [Our tutorials](https://www.cbioportal.org/tutorials) would be useful. You might want to spend the time to fully understand the ideas you are interested in. Please feel free to ask us questions if anything is unclear.

Next, you might want to get familiar with [our code base](https://github.com/cBioPortal/). There are also [good first issues](https://github.com/cBioPortal/cbioportal/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) if you like to get your feet wet.

I would also recommend looking at [how to write a proposal](https://google.github.io/gsocguides/student/writing-a-proposal). We have a proposal template available [here](https://github.com/cBioPortal/GSoC/wiki/template). Once you have a draft proposal please share it with us on google docs so we can give you feedback. You can send the proposal privately to us on [Slack](https://slack.cbioportal.org/).

**Comment by coderrsid** [comment]
Thanks @jjgao. I'll get familiar with your code base and rectify some issues.

**Comment by inodb** [comment]
@jjgao The Hyve has partially implemented the waterfall feature - I guess we still need coloring of the bars by clinical data?

**Comment by jjgao** [comment]
@inodb yes, that would be very useful.

**Comment by hv7214** [comment]
@jjgao i'm willing to take this up. Can you assign this to me ?
