### ISSUE TITLE
Curating ICGC PCAWG data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#64]
**Background**: 

The [ICGC PCAWG dataset](https://dcc.icgc.org/pcawg) has been [published](https://www.nature.com/immersive/d42859-020-00001-y/index.html). It will be a useful dataset for the [public cBioPortal](https://www.cbioportal.org).  

**Goal**: 
Curate the ICGC PCAWG data and make them available on cBioPortal [datahub](https://github.com/cBioPortal/datahub/) and pubic cBioPortal.

**Approach**: 

* Download data from [ICGC Data Portal]( https://xenabrowser.net/datapages/?cohort=PCAWG%20(specimen%20centric)&addHub=https%3A%2F%2Fpcawg.xenahubs.net&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443) and/or [PCAWG Xena Hub]( https://xenabrowser.net/datapages/?cohort=PCAWG%20(specimen%20centric)&addHub=https%3A%2F%2Fpcawg.xenahubs.net&removeHub=https%3A%2F%2Fxena.treehouse.gi.ucsc.edu%3A443).
* Convert the data files into the [cBioPortal-ready formats](https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats)

**Need skills**: 
* Data curation
* Scripting, e.g. Python, for file processing

**Possible mentors**:

**Comment by Akshit312** [comment]
Hi, I want to work on this issue.

**Comment by jjgao** [comment]
@Akshit312 thanks for your interest. Looking forward to seeing your proposal.

**Comment by michiboo** [comment]
Hi I am interested in this project too, can I also write a proposal on this?

**Comment by jjgao** [comment]
@michiboo sure. Looking forward to your proposal.

**Comment by inodb** [comment]
@jjgao should we keep this for GSoC2020?

**Comment by jjgao** [comment]
Yes, it would be great if we can get this dataset into the public portal.

**Comment by ao508** [comment]
todo: update text

**Comment by kpiyush04** [comment]
Hey, @jjgao @inodb @ao508 
I'm **Piyush Kumar** a sophomore student from Galgotias University, Greater Noida, India.
I found this project is very interesting. I'm working on python, data analysis and visualization.
currently, I am looking forward to contributing to open source.
So suggest to me, what I can do further in this project!

**Comment by kpiyush04** [comment]
Hey, @jjgao  @inodb  @ao508 
I'm Piyush Kumar a sophomore student from Galgotias University, Greater Noida, India.
I found this project is very interesting. I'm working on python, data analysis and visualization
currently, I am looking forward to contributing to open source.
So suggest to me, what I can do further in this project!
