### ISSUE TITLE
Mutations tab improvement

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#65]
**Background**: 
[The Mutations tab](http://bit.ly/2EFlBcF) in Results page is very useful for studying details about mutations. But it has it's limitation, for example, only one filter/search is allowed.

![image](https://media.giphy.com/media/4ZknGVFB4EzGLMmTC4/giphy.gif)

We would like to enhance the functionality of this page including improving its filtering/searching capability and options to load clinical attributes.

**Goal**: 
* Implement an option to load clinical attributes
* Improving filtering/searching

**Approach**: 
* To implement the option to load clinical attributes, we can use the same component of "Add Chart" used in [Study View](https://www.cbioportal.org/study?id=msk_impact_2017). A column should be added per selected attribute in the mutations table.

![image](https://user-images.githubusercontent.com/840895/53605725-6f459b80-3b86-11e9-9266-ee8b9a36b543.png)

* Currently, we only list number of mutation by it type, ie. missense, truncating, inframe and other, and allow filtering by type. It would be useful to list and filter by any column in the table (including selected clinical attribute).
  - We might want to consider change the representation to a bar/column chart.
  - Multiple filters should be supported.
  - Filter and table search should be supported simultaneously.

**Need skills**: 

Javascript, REACT

**Possible mentors**: 
@Luke-Sikina @sheridancbio

**Comment by ArexJambusarwala** [comment]
Hey, I am a second year B-Tech student at DAIICT and am aiming for GSOC'19. This issue has caught my eye and I would like to work on it. I have been working on front-end technologies like HTML5/CSS, Javascript and React for over two years. I also have created websites from scratch using these technologies along with PHP. I believe I can make a significant contribution to this project and would like to know how to proceed further with the same.  Thanks!

**Comment by jjgao** [comment]
@ArexJambusarwala thanks for your interest. Looking forward to seeing your proposal.

**Comment by coderrsid** [comment]
Hey @jjgao I have sent you my proposal for this issue on Slack direct message. Can you please review it? and can you please tell me if i could mail you the proposal too?

**Comment by coderrsid** [comment]
Hey @jjgao @inodb I got a little late to submit the proposal because i went to a hackathon outside the city but please consider my proposal too and i have added mockups of filter as @inodb  wanted.

**Comment by inodb** [comment]
@onursumer you think this is feasible for GSoC2020?

**Comment by onursumer** [comment]
@inodb Multiple/simultaneous filter support has already been added and currently functional. We should update the project description to reflect the latest state of the mutations tab.

Implementing UI for additional filter options, like filtering by different columns, should be straightforward now. I am not sure though how much effort required to load clinical attributes.

**Comment by onursumer** [comment]
Maybe we can also include cBioPortal/cbioportal/issues/5607 as part of this. @inodb, @jjgao, what do you think?

**Comment by jjgao** [comment]
@onursumer good idea 👍

**Comment by Dharmesh-Poddar** [comment]
@jjgao @onursumer can you please guide me for this project :)

**Comment by sheridancbio** [comment]
I have added myself as a possible mentor ... although I would not be good as the primary/sole mentor. If I participate I will also be improving my knowledge of our frontend/react development.
