### ISSUE TITLE
Clonal Evolution

### ISSUE THREAD

**Issue by fongcj** [cBioPortal/GSoC#66]
**Background**: 
Genetic sequencing has confirmed that many cancers are evolutionarily heterogeneous. As a tumor grows, new mutations accumulate in individual cells, and as these cells replicate, the mutations are passed on to their offspring, which comprise only a portion of the tumor when it is sampled. As a result, A key challenge in cancer genomics is the genomic heterogeneity seen within tumors. For example, two biopsies from different sites of the same tumor may have very different mutations. Likewise, a tumor biopsy taken after treatment may show the emergence of new resistance mutations that were not detected in the original sample. Reconstruction of clonal evolution provides insight into tumor heterogeneity, evolution, and treatment response, all of which may have clinical implications.  

For general background, see:

[What is Tumor Heterogeneity?](https://www.mskcc.org/blog/what-tumor-heterogeneity), Memorial Sloan-Kettering Cancer Center. July 2, 2014.
[A Deeper Look at Tumor Heterogeneity](http://cancerdiscovery.aacrjournals.org/content/2/8/660.full), Cancer Discovery 2012.

**Goal**: 
This project aims to implement a feature visualizing clonal ordering and evolution in [cBioPortal](https://www.cbioportal.org).  There are two visualizations that can represent this
Bell plots (Fishplot) to present clonal dynamics over time 
Phylogenetic Tree, or branch based tree to present clonal subpopulations of a sample

Example (via https://github.com/hdng/clonevol):

Fish plot 
<img width="849" alt="screen shot 2019-02-27 at 5 26 00 pm" src="https://user-images.githubusercontent.com/25805540/53670409-a4b2bd80-3c48-11e9-9b5c-2fe16556b5a9.png">
-----------

Node or branch based phylogenetic tree
<img width="352" alt="screen shot 2019-02-27 at 5 36 53 pm" src="https://user-images.githubusercontent.com/25805540/53670421-b005e900-3c48-11e9-8883-c09af9c8bc3a.png">
-----------

Simplified bell plot, representing the same data as the fish plot
<img width="308" alt="screen shot 2019-02-27 at 5 42 33 pm" src="https://user-images.githubusercontent.com/25805540/53670431-b85e2400-3c48-11e9-8528-09f5b9c0ea16.png">
-----------

**Approach**: 
Part 1. Provided a MAF file containing mutation calls, perform data manipulations specific to one (or more) of the clonal evolution algorithms.

Potential implementations:
ClonEvol (https://github.com/hdng/clonevol) - R (Most mature software package)
clonal_evolution_summary  (https://github.com/fongcj/clonal_evolution_summary) - Python (Basic Visualizations)
PyClone (https://github.com/aroth85/pyclone) - Python (No visualizations provided)

Output of these algorithms should be a table containing information to produce the fish, bell, and/or phylo-tree.  As part of the proposal, the inputs and outputs of the algorithm implementation should be addressed.  

For example, from the clonal_evolution_summary code, prototype now, there would be 3 inputs: mutation maf and CNA calls, and a dictionary of the patient's sample IDs and relative time points (0,1,2.. etc. or dates)
The script will output the follow table:
<img width="1302" alt="screen shot 2019-02-27 at 6 26 17 pm" src="https://user-images.githubusercontent.com/25805540/53670452-c8760380-3c48-11e9-9d8c-abb307f3eaf2.png">

Part 2. Implement the visualization components of fish, bell and phylo-tree in Javascript/REACT.

Again, using the clonal_evolution_summary code as an example, the output table provides information to produce a simple tree using Pythons networkx library. Using a separate function,  a visualization of a phylo-tree can be produced:
![evolution__232](https://user-images.githubusercontent.com/25805540/53670541-168b0700-3c49-11e9-9917-57a3dff3383c.png)

**Need skills**: 
R and/or Python (Pandas), Javascript

**Possible mentors**: 
Chris F.

**Comment by lokeshrana9999** [comment]
Hey, I am student of Biotech(IIT Guwahati). I have been working with reactjs for the last year or so. I would like the opportunity to work on this issue. 
Thank You

**Comment by pcalderong** [comment]
Hello @jjgao, I'm currently studying BioInformatics, and I found this project really interesting to gain some experience in the field and support such a helpful platform. I just have one question, Where can I find the steps to submit a proposal to work on this project?
Thanks.

**Comment by jjgao** [comment]
@pcalderong thanks for your interest. The deadline to apply to this project as a GSoC student has passed: https://developers.google.com/open-source/gsoc/timeline. If you are interested in contribute to cBioPortal open source project, our source code is here: https://github.com/cBioPortal/. Please let us know and we will get your started.

**Comment by inodb** [comment]
A very good prototype was developed in GSoC2019 for 2020 we should prolly finish bringing this to production ourselves
