### ISSUE TITLE
Add Mutation Diagram on Study View for Enhanced Mutation Analysis

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#67]
**Background**: 
The Study View (e.g. [MSK-IMPACT 2017 study](https://www.cbioportal.org/study?id=msk_impact_2017)) of cBioPortal provides a powerful interactive way for exploring clinical and genomic data in a study (cohort of samples). 

![image](https://user-images.githubusercontent.com/840895/53684831-741e6280-3ce0-11e9-9070-eb0076449b63.png)

**Goal**: 
The overall goal of this project to enhance its capability for analyzing mutations. Specifically:
- Visualizing mutations in a gene with [mutation diagram](http://bit.ly/2tKqafv)
  - Each gene in the `Mutated Genes` table can have a submenu or icons that can lead to adding a mutation diagram
![image](https://user-images.githubusercontent.com/840895/53684805-29044f80-3ce0-11e9-8464-6f2259dc32cc.png)
- The added mutation diagram should be interactive with other charts
  - When the use selects samples with other charts, the mutation diagram will only show mutations for the selected samples
  - When selecting one or more mutations in the mutation diagram, the other charts will also reflect based on the selected samples.
  - Allow user to select a range
  - Allow zoom in

**Approach**: 
The REACT component that is used in the Mutations tab should be reused here. Enhancement will be needed, e.g. zooming capability.

**Need skills**: 
Javascript, REACT

**Possible mentors**:

**Comment by prasadgujar** [comment]
Hello @jjgao can I take this issue to solve?

**Comment by coderrsid** [comment]
@jjgao Can i add issue #63 and this issue and work on it together in my proposal for GSOC and can you suggest any other similar issue you think i can work on so that i can do more work in less time?

**Comment by lokeshrana9999** [comment]
Hey @jjgao , I am student of Biotech(IIT Guwahati). I have been working with reactjs for the last year or so. I would like the opportunity to work on this issue.
Thank You

**Comment by hv7214** [comment]
@inodb can you help me get started with this project ? I am willing to take this up for gsoc20.
