### ISSUE TITLE
Tumor heterogeneity / evolution view in patient view

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#7]
**Background**:   A key challenge in cancer genomics is the genomic heterogeneity seen within tumors. For example, two biopsies from different sites of the same tumor may have very different mutations. Likewise, a tumor biopsy taken after treatment may show the emergence of new resistance mutations that were not detected in the original sample.

For general background, see:

[What is Tumor Heterogeneity?](https://www.mskcc.org/blog/what-tumor-heterogeneity), Memorial Sloan-Kettering Cancer Center. July 2, 2014.
[A Deeper Look at Tumor Heterogeneity](http://cancerdiscovery.aacrjournals.org/content/2/8/660.full), Cancer Discovery 2012.

**Goal**:  Extend the current patient view within the cBioPortal to enable more effective visualization of tumor heterogeneity within a single patient.  For some inspiration, [see slides from last year for our OncoBlocks KingFisher application](https://drive.google.com/folderview?id=0B-c5jwGzSQyPOHZyUVdNV2hFRUk&usp=sharing).

A screenshot of the existing patient view displaying multiple samples for one patient is provided below:

![screenshot_667](https://cloud.githubusercontent.com/assets/1009066/12875449/9ab20cb6-cdb8-11e5-95b8-bc4a2d584f6d.png)

We are interested in any clever ideas you may have to better represent / visualize this data.  For example, imagine how you might represent 20 samples for one patient;  how you might highlight or animate changes over time; how you might draw the user's eye to specific differences in each sample, etc.

**Need skills**:   Bioinformatics, Data Visualization, Java, Javascript.

**Possible mentors**:   Ethan Cerami,  [Angelica Ochoa](https://github.com/angelicaochoa)

**Comment by yasirunilan** [comment]
Hi,

I'm Yasiru Nilan, 3rd year student from department of computer Science and Engineering,University of Moratuwa,Sri Lanka.I went through all the details about this particular issue and I'm happy to work on this.Is there any way to get more information about this one.Also I'm familiar with web development and these days I'm referring to cBioPortal also.

Thanks in advance.

**Comment by jjgao** [comment]
@yasirunilan you could start with getting familiar with [KingFisher](https://github.com/oncoblocks/kingfisher). One main goal is to use KingFisher in the cBioPortal Patient page (e.g. http://www.cbioportal.org/case.do?cancer_study_id=lgg_ucsf_2014&case_id=P04)

**Comment by yasirunilan** [comment]
Thank you, I will look in to kingfisher.
Yasiru Nilan

BSc. Eng(Hons) Undergraduate |Batch Representative CSE'13 Batch
Department of Computer Science and Engineering |University of Moratuwa |
Sri Lanka

Asst. Secretory | Leo Club of University of Moratuwa | Leo District 306A2

**Comment by Yasara123** [comment]
@jjgao @angelicaochoa  Is this project still up? i'd like to contribute. will it be possible?
