### ISSUE TITLE
PathwayMapper viewer and editor improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/GSoC#73]
**Background**:
While the previous network visualization module in cBioPortal was a powerful exploration tool, most biologists are more comfortable with the kind of simplified, curated pathway diagrams that are featured in many manuscripts from The Cancer Genome Atlas (TCGA). With the motivation of creating a platform that provides more intuitive pathway diagrams, yet supports these with rich data ‘decoration’ and analysis with access to data in cBioPortal, with attractive visualization, we developed a tool named [PathwayMapper](https://github.com/iVis-at-Bilkent/pathway-mapper) [1], and are in the process of integrating it into cBioPortal.

**Goal**: 
The goal of this project is to improve PathwayMapper in cBioPortal as well as enhancing the full-blown, stand-alone editor version as follows.

***PathwayMapper viewer in cBioPortal***
- Add Pathways tab to Study View page ([example](https://www.cbioportal.org/study/summary?id=msk_impact_2017)): map frequencies of mutations, CNAs, and fusions in the cohort to pathways, ranking similarly to the results page.
- Add Pathways tab to Patient View page ([example](https://www.cbioportal.org/patient?studyId=msk_impact_2017&caseId=P-0012360)): map mutations, CNAs, and fusions to pathways, ranking similarly to the results page
- Add Pathways tab to Comparison page ([example](https://www.cbioportal.org/comparison/mutations?sessionId=5cf89323e4b0ab413787436c)): map frequencies in different groups to pathways. Pathways should be ranked by the "difference" between the groups.
- Currently available pathways are matched to genes of interest by count or percentage and ranked using this score. Alternative or better ranking schemes should be investigated and implemented.
- Resolve several miscellaneous outstanding issues/bugs

***PathwayMapper editor***
- Expand-collapse and hide-show operations should be integrated (via associated Cytoscape.js extensions) for complexity management.
- Filtering (by alteration percentage) and highlighting capabilities should be incorporated.
- Collaborative mode in the editor is based on SharedDB and seems to work OK for the most part but every now and then it breaks. This is a serious issue that needs to be carefully debugged and fixed.
- All third party libraries need to be upgraded.
- Resolve several miscellaneous outstanding issues/bugs

[1] I. Bahceci, U. Dogrusoz, K.C. La, Ö. Babur, J. Gao, N. Schultz, "PathwayMapper: a collaborative visual web editor for cancer pathways and genomic data", Bioinformatics, 33(14), pp. 2238-2240, 2017.

**Approach**: 
This project requires you to work on both PathwayMapper and cBioPortal repositories and be mostly experience in doing front-end work.

**Need skills**: 
Good programming skills and experience in web technologies (JavaScript, html, css), especially knowledge of React, is required.  Familiarity with visualization software (PathwayMapper is based on [Cytoscape.js](http://js.cytoscape.org)) is a big plus.

**Possible mentors**: 
[Ugur Dogrusoz](https://github.com/ugurdogrusoz)
[S.Onur Sumer](https://github.com/onursumer)
[Alexander Pico](https://github.com/AlexanderPico)

**Comment by AlexanderPico** [comment]
Happy to co-mentor this (if it gets selected) for possible WikiPathways and Cytoscape Ecosystem integrations.
