### ISSUE TITLE
"Hint" mode for cBioPortal and OQL editor

### ISSUE THREAD

**Issue by alisman** [cBioPortal/GSoC#74]
**Background**: The portal has a lot of "hidden" features.  Features which a large percentage of users don't even know about because they lack prominence in the UI. For example, group comparison, oql qualifiers in gene box.

**Goal**: 
To provide hints in the UI when hint mode is turned on.  These would appear in prominent parts of the page.  We would certainly want to make them dimissable and hideable by mode. 

For the gene entry box, we could show a little hint message in proximity to the entry field that would advise users of the existence of modifiers like : MUT etc.

**Need skills**: 
React, css, UI design

**Possible mentors**: 
Aaron

**Comment by inodb** [comment]
Looks like there might be some overlap with this one: https://github.com/cBioPortal/GSoC/issues/75?

**Comment by alisman** [comment]
@inodb @adamabeshouse agreed.  i stuck these two together because i wasn't sure the hint mode was "enough" for a full project.  What do you think?  Is it too menial/basic?   As for the OQL hinting, the scope of that project depends on how fancy we make the UI.

**Comment by inodb** [comment]
@alisman I think just OQL hinting might be enough. We have not gotten that many projects of GSoC to production so might be nice to do some simpler projects. We can always extend during the course of the project. There are a lot of things that need to be learned to really get it to completion I think e.g. adding tests for the hinting, properly writing the description of the PR, proposing a news item

**Comment by inodb** [comment]
The non oql hint mode part sounds like it might have some similarities with the interactive web tour: #29

**Comment by inodb** [comment]
I closed this one and change the interactive web tour: https://github.com/cBioPortal/GSoC/issues/29
