### ISSUE TITLE
Add some form of cohort selection to the oncoprint

### ISSUE THREAD

**Issue by alisman** [cBioPortal/GSoC#76]
**Background**: 
It might be nice to be able to assemble a cohort in the Oncoprint itself, either by clicking one-by-one on the columns or using a draggeable selection area.

**Goal**: 

**Need skills**: 
Javascript, UI design

**Possible mentors**: 
Aaron, Adam

**Comment by jjgao** [comment]
This is a great idea! We can allow the user to open the selected samples/patients and create groups from them.

I am wondering if the workload is enough for 3 months? Maybe we can extend it to other tabs, e.g. Mutations, Plots, Expression, etc?
