### ISSUE TITLE
Improve Quick Search for Patients and Samples

### ISSUE THREAD

**Issue by Luke-Sikina** [cBioPortal/GSoC#77]
**Background**: 
Quick search is a way to view studies, genes, patients and samples quickly from the main page of the website. You can see quick search in action by going to [cbioportal.org](https://www.cbiportal.org), clicking on the `Quick Search` tab, and entering something in the search bar (`BRAF` will get you a good spread of results).
Right now, quick search looks for patients and samples in a pretty primitive manner. For samples it just matches on sample ID, and for patients it matches to the patient ID or the ID's of the patient's samples.

**Goal**: 
Make quick search for patients and samples match on genes the patient has mutations in, associated protein changes, clinical attributes, and clinical events.

**Approach**: 
All file paths referenced in this section refer to paths within the [cbioportal backend repo](https://github.com/cBioPortal/cbioportal).

The current matching logic for patients resides in `src/main/resources/org/cbioportal/persistence/mybatis/PatientMapper.xml`; the logic for samples is in `src/main/resources/org/cbioportal/persistence/mybatis/SampleMapper.xml`. These files need to be changed so that `keyword` matches on the patient/sample's mutated genes, corresponding protein changes, clinical attributes, and clinical events. These pieces of information are stored on different tables; to see the relationships between the tables, you can either look at `src/main/resources/cgds.sql` or you can look at [this database diagram](https://raw.githubusercontent.com/cBioPortal/cbioportal/master/db-scripts/src/main/resources/cbioportal-er-diagram.png).

These endpoints are called as you type in the quick search bar, so the endpoints have to remain performant even though you're adding functionality. Try to keep response times subsecond.

**Need skills**: 
SQL, Java

**Possible mentors**: 
Luke

**Comment by pieterlukasse** [comment]
Nice 👍 . Maybe also include finding patients/samples by clinical events (aka timeline entries).

**Comment by Luke-Sikina** [comment]
I understand the concerns about this being too complex given how we want to display the results. I'm going to close this issue for now so that no one gets confused.
