### ISSUE TITLE
Single command to run cBioPortal (Docker Compose & Helm Chart)

### ISSUE THREAD

**Issue by inodb** [cBioPortal/GSoC#78]
**Background**: 
Our current recommended way of deploying cBioPortal requires the user to run several docker commands to get cBioPortal running: https://docs.cbioportal.org/2.1.1-deploy-with-docker-recommended/docker. Ideally there would be a single command with further explanation of how the different parts are connected. A common approach for launching multiple Docker services is using Docker Compose. That allows you to start the whole system with one command: `docker-compose up`. Aside from using Docker Compose it would be nice if a way to start the system using kubernetes was provided. For kubernetes helm is often used to set up a complete system. A single command like `helm install --name cbioportal cbioportal` should set up all services required for cBioPortal with reasonable defaults.

**Goal**: 
Provide a single command to run cBioPortal

**Approach**: 
- Provide a Docker Compose file to launch cBioPortal
- Provide a Helm Chart to launch cBioPortal
- Bonus: Provide some way to automatically validate and load data from a folder into cBioPortal by mounting some volume with example studies. Importing a study should be a matter of adding some folder.

**Need skills**: 
- Familiarity with command line
- Docker and Kubernetes familiarity is a plus but can be learned during GSoC

**Possible mentors**: 
@inodb @dippindots @leexgh

**Comment by aditya300899** [comment]
I'd like to do this project. Please guide me accordingly.

**Comment by Dharmesh-Poddar** [comment]
@inodb I would like to work on this project.
