### ISSUE TITLE
Adding an AI based chat-bot to the website 

### ISSUE THREAD

**Issue by Vivek1258** [cBioPortal/GSoC#79]
**Background**: 

With more new features being added into cBioPortal, it might become confusing for new users to utilize the site. Adding an AI-based chatbot system to the website would help to increase the user experience, understand the general problems faced by a user, etc.

**Goal**: 

1. To develop an AI-based chat-bot system from scratch.
(create a chatbot and inject some true personality into the way we communicate with our potential clients, for example, researchers, clinicians, etc. )
2. To implement the system to the website 

 
**Need skills**: 
Natural language processing (NLP), ML, Python, JavaScript, CSS. 

**Possible mentors**: 
@inodb

**Comment by inodb** [comment]
Hi @Vivek1258 ! Thanks so much for sharing your idea!

Just curious: are you interested in applying to GSoC as a student? Were you looking to get feedback on the idea? Thanks!

**Comment by Vivek1258** [comment]
Hi

Thanks for the reply
 
Yes I am interested to apply in GSoC 2020 

and am very keen on the cBioPortal website because I am a  WEB and  ML enthusiast who has done his Higher Secondary Education In the Field of Biology.

Thanks Again

**Comment by inodb** [comment]
Thanks @Vivek1258 ! Nice to meet you & great to hear! 

Take a look at our cBioPortal contributing guide: https://github.com/cBioPortal/cbioportal/blob/master/CONTRIBUTING.md
and our wiki on GSoC here: https://github.com/cBioPortal/GSoC/wiki

We have a few issues labeled as “good first issue” to get familiar with contributing code: https://github.com/cbioportal/cbioportal/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22.

Do note that nothing is official yet from Google. We will apply again this year, but it’s not certain we’ll get accepted.

I will close this idea issue for now. It's an interesting project, you could convert it to a proposal once applications open. I can give some feedback on slack if you want to get feedback before sending it in: https://slack.cbioportal.org Thank you!
