### ISSUE TITLE
Continue ETL pipeline development for TCGA data from GDC Portal

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#8]
**Background**: 
The [Genomic Data Commons (GDC) data portal](https://portal.gdc.cancer.gov/) hosts a variety of large-scale cancer genomics data from projects including TCGA, TARGET, Foundation Medicine, and others. Data for these projects are available for public use and can be downloaded programmatically through the [GDC API](https://gdc.cancer.gov/developers/gdc-application-programming-interface-api).

Datatypes include:
- clinical 
- sequencing reads
- simple nucleotide variation 
- transcriptome profiling
- copy number variation
- combined nucleotide variation
- DNA methylation

These are collected using a variety of assays, such as WXS/WGS, RNA-seq, miRNA-seq, methylation arrays, etc. 

**Goal**: 
The overall goal of this project is to continue the development of an ETL pipeline for TCGA data from the GDC Portal and expand the pipeline to handle and process additional datatypes. The student will prioritize adding copy number variation data. If time allows, the student may also begin adding support for additional datatypes.

In its current state, given a GDC manifest file, the pipeline converts a subset of clinical data and mutation data from the GDC portal into the expected file formats for importing into the cBioPortal. 

**Approach**: 
Existing development efforts of this pipeline can be reviewed [here](https://github.com/cBioPortal/gdc-et-pipeline/tree/gsoc-development) and the `README` is available [here](https://github.com/cBioPortal/gdc-et-pipeline/blob/master/README.md). [Spring Batch](https://spring.io/projects/spring-batch) should be used to expand the pipeline to handle and process additional datatypes. Development efforts are expected to be integrated into the existing workflow as well.

Accepted file formats for the cBioPortal are detailed [here](https://docs.cbioportal.org/5.1-data-loading/data-loading/file-formats).

**Need skills**: 
The ideal candidate will have some experience with the following:
- Java (Spring, Spring-Batch), REST/API services, basic command line tools

**Resources**
- [GDC Data Dictionary Viewer](https://docs.gdc.cancer.gov/Data_Dictionary/viewer/)
- [GDC Data Dictionary (yaml-based schemas)](https://github.com/NCI-GDC/gdcdictionary)
- [GDC Data Dictionary (json-based schemas)](https://docs.gdc.cancer.gov/API/Users_Guide/Submission/#gdc-data-dictionary-endpoints)

**Possible mentors**: 
@ao508 @n1zea144  @sheridancbio

**Comment by evgerher** [comment]
Hello @jjgao,
I am interested in this project and #68 and wish to write a good proposal.
Do you have any test-task?
How can I contact you through mail?
What can you suggest to focus on?

**Comment by jjgao** [comment]
@evgerher sorry I was on travel and your questions fell between the cracks. Please let me know if you still need info.
