### ISSUE TITLE
Body map showing locations of sequenced samples in patient view

### ISSUE THREAD

**Issue by fongcj** [cBioPortal/GSoC#81]
**Background**: 
The cBioPortal Patient Viewer gives researchers an in-depth view of individual patients, providing a view of their specific gene alterations, CN alterations across the genome, as well as a clinical timeline of sequenced samples and other clinical events.  

<img width="1423" alt="Screen Shot 2020-01-29 at 11 52 46 AM" src="https://user-images.githubusercontent.com/25805540/73378650-eac83500-428e-11ea-9eef-bace76f6f9f0.png">

However, when analyzing a patient's clinical history, researchers must use their imagination to understand the context of where these sequenced samples have been biopsied from in the body.  

To provide better clinical context, a visualization of the human body can be shown along side the patient timeline to highlight the region(s) of sequenced samples.

**Goal**: 
A visualization of the body map can be integrated along side the patient timeline. Overlaid on the body map would be markers of interest where a patient had a sample sequenced, biopsied, and/or had a surgical procedure. 
The markers on the body would have a hover-over feature that would provide metadata of the sample and highlight the corresponding marker shown on the patient timeline.
The provided sample locations would be normalized to a set of anatomic locations, which is to be determined. 

Below is a poorly photoshopped idea of what the result could be:
<img width="1423" alt="Screen Shot 2020-01-29 at 11 52 46 AM copy" src="https://user-images.githubusercontent.com/25805540/73380098-6fb44e00-4291-11ea-8d4e-c43152dc0994.png">

**Approach**: 
- Create and embed a vectorized body map.
- Create a mapping of normalized body locations to specific regions on the body map.
- Overlay points of sequenced sites onto the body map.
- Link points of sequenced sites to the patient timeline, make the points pop-up if mouse is hovered over the point on timeline or on body map.
- Also provide metadata of sequenced sample/biopsy/surgery when hovering over point.
- Create option to save bodymap with points of interest.
- Create option to expand and compress the body map image for increased clarity.

**Need skills**: 
Javascript, HTML

**Possible mentors**: 
Co-mentor: @fongcj

**Comment by TheWizard25** [comment]
Hi,
I want to work on this idea for my GSOC'20 project. Can you guide me a little about how to start? Please share some tutorials/guides/blogs/documentation if available so that I can make myself familiar with cBioPortal. 
Thank you
