### ISSUE TITLE
Unite Backend Configuration Handling

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/GSoC#82]
**Background**: 
Configuration of the backend web application has gone through several eras, and there are now several legacy mechanisms available for configuring cBioPortal.

The backend is packaged as a web archive (war), and the oldest form of configuration is embedding a [properties file](https://github.com/cBioPortal/cbioportal/blob/v3.2.1/src/main/resources/portal.properties.EXAMPLE) in the web archive file. Originally, the properties in this file were fully modeled with class data members in class [GlobalProperties](https://github.com/cBioPortal/cbioportal/blob/v3.2.1/core/src/main/java/org/mskcc/cbio/portal/util/GlobalProperties.java) and access was through get and set member functions.

Over time, access to properties and the setting of default values migrated partially throughout the codebase using spring `@Value` annotations and the bean post processing mechanism. [example](https://github.com/cBioPortal/cbioportal/blob/v3.2.1/service/src/main/java/org/cbioportal/service/impl/UuidDataAccessTokenServiceImpl.java#L55) [example](https://github.com/cBioPortal/cbioportal/blob/v3.2.1/web/src/main/java/org/cbioportal/web/InfoController.java#L22)

Also, a mechanism was introduced to allow arbitrary properties to be read ... either from the properties file or from the JVM runtime environment, and these would be stored in a Dictionary in an [embedded class](https://github.com/cBioPortal/cbioportal/blob/v3.2.1/core/src/main/java/org/mskcc/cbio/portal/util/GlobalProperties.java#L338)

There is also an [old mechanism](https://github.com/cBioPortal/cbioportal/blob/v3.2.1/business/src/main/resources/applicationContext-business.xml#L20) for reading properties from an external portal.properties file based on a path set in the runtime environment.

Currently, the project is moving away from building in configuration settings into cBioPortal deployments. To aid in containerized deployments, we pass configuration to the web application through
**java -D**_property_name_=_property_value_ command line settings or environment variables. As much as possible, it would be good to eliminate older forms of configuration management.

**Goal**: 
The goal of this project is to reduce the variety of property setting and property getting modes in the codebase in order to make the code more elegant and consistent (refactoring).

**Approach**: 
- A survey of the code would be done to identify the uses of various property management mechanisms.
-  If feasible, the class GlobalProperties would be eliminated. If not, the explicit modeling and default selection of property values would be eliminated and only the general Dictionary storage mechanism would be used.
- Other business logic in GlobalProperties [example](https://github.com/cBioPortal/cbioportal/blob/v3.2.1/core/src/main/java/org/mskcc/cbio/portal/util/GlobalProperties.java#L904) beyond the storing of explicit property values would be relocated to standalone classes.
- Default values, and the coordination of default values across the codebase would be considered and if possible, a standardized approach would be adopted which avoided code duplication of default values in many places.
- Documentation would be updated, and if possible, a programmatic approach for documenting and reporting the configuration properties and default values present across the codebase would be made available as a tool or by adopting the appropriate maven repository library.

**Need skills**: 
Java
Spring Expression Language (SPeL) helpful
Maven Project Configuration

**Possible mentors**: 
@sheridancbio

**Comment by jjgao** [comment]
@sheridancbio I am wondering if it's time to develop an Admin page? That way, we could deliver a war/jar for people to deploy and configure.

**Comment by sheridancbio** [comment]
@jjgao that would also be a great project. A webpage would come up and give you options to set ... database connections, skin settings, user authentication policies/provider, etc. Perhaps it could also include in our hope to operate a single web server which hosts multiple portals/URLs with mappings of skins to request URL base name and database sources (and that could be dynamically reconfigurable)

There are other administrative functions which would be helpful too ... including recaching of study data after imports have occurred. That way restarts would no longer be necessary.
