### ISSUE TITLE
Broader use of pathway views in cBioPortal

### ISSUE THREAD

**Issue by ugurdogrusoz** [cBioPortal/GSoC#85]
**Background**:

Pathway diagrams are widely used in genomics to describe changes occurring in signaling pathways resulting from genomic alterations. There are [several tools](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4461095/) available to facilitate the visualization and analysis of pathway alterations, including [PathwayMapper](https://github.com/iVis-at-Bilkent/pathway-mapper).

[PathwayMapper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5859976/) is a _collaborative_ visual web editor for cancer pathways and genomics data, that also allows users to enrich pathway diagrams by overlaying genomic alteration data, and provides an interactive graphical editing tool for creating and modifying pathways. 

PathwayMapper [1] has also been integrated into the [cBioPortal for Cancer Genomics](https://cbioportal.org/), an open-access, open-source resource for interactive exploration of multidimensional cancer genomics data sets. For an overview on the cBioPortal, please refer to the [home page](https://www.cbioportal.org). 

When users query a cancer study on the cBioPortal for genes of interest, they are taken to a new page containing various visualizations and reports for analysis that users can navigate to by selecting the desired tab. The **Pathways** tab is where users can view the available cancer pathways which are matched to the genes of interest by count or percentage and ranked using this score. See the example provided below and/or [follow this link](https://bit.ly/3HrJUrv) to see the Results page and available reports/visualizations yourself.

**Figure 1. Example Pathways tab view. Queried genes: TP53, KRAS, PIK3CA, TERT.**

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/15623749/155810015-f4496395-7969-4770-9e19-0e508a51533f.png">

While highly useful, the integration of PathwayMapper into the cBioPortal can be further improved through the addition of features like allowing users to overlay data on pathways on the fly, for example. 

---

**Goal**: 

The goal of this project is to improve the integration of PathwayMapper into cBioPortal as well as enhancing the full-blown, stand-alone editor version as follows.

***PathwayMapper viewer in cBioPortal***

- Add Pathways tab to Comparison page ([example](https://www.cbioportal.org/comparison/mutations?sessionId=5cf89323e4b0ab413787436c)): map frequencies in different groups to pathways. Pathways should be ranked by the "difference" between the groups.

- Currently available pathways are matched to genes of interest by count or percentage and ranked using this score. Alternative or better ranking schemes should be investigated and implemented.

- Resolve several miscellaneous outstanding issues/bugs

***PathwayMapper editor***

- The overall architecture should be revisited to properly address different views in different context (e.g. full PathwayMapper editor vs PathwayMapper in Comparison Page vs PathwayMapper in Patient View).

- Expand-collapse and hide-show operations should be integrated (via associated Cytoscape.js extensions) for complexity management.

- Filtering (by alteration percentage) and highlighting capabilities should be incorporated.

- Collaborative mode in the editor is based on SharedDB and seems to work OK for the most part but every now and then it breaks. This is a serious issue that needs to be carefully debugged and fixed.

- All third party libraries need to be upgraded.

- Resolve several miscellaneous outstanding issues/bugs

***Exchange Pathways with NDEx***

Another popular pathway tool is [NDEx](https://pubmed.ncbi.nlm.nih.gov/34570431/) [2]. This tool has a slightly different approach in that it mines pathways from literature and public databases, whereas PathwayMapper is more focused on collaborative manual editing of pathways. There is an integration in development to allow use of these pathways in cBioPortal as well (see [related Pull Request](https://github.com/cBioPortal/cbioportal-frontend/pull/4069)). We would like to make the pathway sharing of PathwayMapper with NDEx more seamless:

- Export pathways from PathwayMapper into NDEx

[1] I. Bahceci, U. Dogrusoz, K.C. La, Ö. Babur, J. Gao, N. Schultz, "PathwayMapper: a collaborative visual web editor for cancer pathways and genomic data", Bioinformatics, 33(14), pp. 2238-2240, 2017.

[2] Pillich RT, Chen J, Churas C, Liu S, Ono K, Otasek D, Pratt D. NDEx: Accessing Network Models and Streamlining Network Biology Workflows. Curr Protoc. 2021 Sep;1(9):e258

**Approach**: 

This project requires you to work on both PathwayMapper and cBioPortal repositories and be mostly experience in doing front-end work.

---

**Needed skills**: 

- Good programming skills and experience in web technologies (JavaScript, html, css)
- Knowledge of React is required  
- Familiarity with visualization software is a big plus. (PathwayMapper is based on [Cytoscape.js](http://js.cytoscape.org)) 

**Possible mentors**: 

@onursumer @ugurdogrusoz

**Comment by aaryahjolia** [comment]
I know frontend development techstack like html,css,js and reactJS a bit. I can eventually learn the techstack required for the project. Is this much enough to work on this issue?

**Comment by ao508** [comment]
> I know frontend development techstack like html,css,js and reactJS a bit. I can eventually learn the techstack required for the project. Is this much enough to work on this issue?

Thank you for your interest in this project! I will be sure to reach out to the mentors listed to let them know to follow up with you.

**Comment by MuluhGodson** [comment]
Hello @ao508 
I am very much interested in working on this.

**Comment by ao508** [comment]
@MuluhGodson Wonderful! Please feel free to begin working on the proposal and do not hesitate to reach out if you have any questions.

**Comment by MuluhGodson** [comment]
@ao508 I'm not able to get in touch with any of the mentors. I left messages privately on Slack about 12 days ago but haven't received a response yet.

**Comment by ugurdogrusoz** [comment]
@MuluhGodson I don't check Slack much. You can email me privately ([home page](http://www.cs.bilkent.edu.tr/~ugur/)).

**Comment by ao508** [comment]
I’m so sorry you’re having trouble reaching them.

I’ll nudge them again but in  the meantime please feel free to begin the
proposal. If you’re looking for any feedback you may share a google doc
link with us.

**Comment by ugurdogrusoz** [comment]
A [project](https://summerofcode.withgoogle.com/programs/2022/projects/FzzHizYK) based on this idea was already done as part of GSoC 2022.
