### ISSUE TITLE
Mutations Tab Enhancements (Clinical Attributes and Search)

### ISSUE THREAD

**Issue by inodb** [cBioPortal/GSoC#89]
**Background**: 
[The Mutations tab](http://bit.ly/2EFlBcF) in Results page is very useful for studying details about mutations. But it has its limitation, for example, only one filter/search is allowed.

![image](https://media.giphy.com/media/4ZknGVFB4EzGLMmTC4/giphy.gif)

We would like to enhance the functionality of this page including improving its filtering/searching capability and options to load clinical attributes.

**Goal**: 
* Implement an option to load clinical attributes
* Improving filtering/searching

**Approach**: 
* To implement the option to load clinical attributes, we can use the same component of "Add Chart" used in [Study View](https://www.cbioportal.org/study?id=msk_impact_2017). A column should be added per selected attribute in the mutations table.

![image](https://user-images.githubusercontent.com/840895/53605725-6f459b80-3b86-11e9-9266-ee8b9a36b543.png)

* Currently, we only list number of mutation by it type, ie. missense, truncating, inframe and other, and allow filtering by type. It would be useful to list and filter by any column in the table (including selected clinical attribute).
  - We might want to consider change the representation to a bar/column chart.
  - Multiple filters should be supported.
  - Filter and table search should be supported simultaneously.

**Need skills**: 

Javascript, REACT

**Possible mentors**: 
@onursumer @leexgh @Luke-Sikina

**Comment by jjgao** [comment]
For filtering, it would be nice to have column-based filter https://github.com/cBioPortal/icebox/issues/140
