### ISSUE TITLE
OncoKB API and public facing web site

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/GSoC#9]
**Background**: 

**Goal**: 

**Approach**: 

**Need skills**: 

**Possible mentors**:

**Comment by ecerami** [comment]
@jjgao since OncoKB is mostly proprietary, perhaps not a good option for GSOC?

**Comment by schultzn** [comment]
Agreed. We are trying to open it up more, but can't promise anything right now.

**Comment by jjgao** [comment]
good point. I'll close this.
