### ISSUE TITLE
Create clinical trial curation tool based on CTML from MatchMiner

### ISSUE THREAD

**Issue by zhx828** [cBioPortal/GSoC#96]
**Background**: 
cBioPortal will include the clinical trial suggestions based on sample genomic data and clinical data. To match the patient with clinical trial, we need to curate trials by going through the eligible criteria(inclusion/exclusion) and identify whether there is any genomic biomarker that trial requires.

To accurately curate/manage clinical trial biomarkers, we will follow the CTML format to curate all precision medicine trials on a platform. The CTML format is defined by MatchMiner. MatchMiner(https://matchminer.org/) is an open source computational platform developed by the Knowledge Systems Group at Dana-Farber Cancer Institute (DFCI) for matching patient-specific genomic profiles to cancer precision medicine trials. OncoKB™ has previously worked on the curation platform 4 years ago and it was written in Angular. Over the years, our tech stack has been updated and we need to refactor the component as a stand-alone react component so all other projects can utilize.

**Goal**: 
Create a react component for trial curation. The component will use firebase for realtime editing.
![Screen Shot 2023-02-07 at 3 27 57 PM](https://user-images.githubusercontent.com/5400599/217369671-d7fd5d07-1da8-4245-8556-14c40afa8448.png)

**Approach**: 
- get familiar with CTML, MatchMiner, OncoKB
- get familiar wit React and Firebase
- look through the previous implementation and understand how the project works
- implement all logics in React

**Need skills**: 
Javascript, typescript

**Possible mentors**: 
Hongxin Zhang(@zhx828 )

**Comment by Player256** [comment]
Hello there I am interested in this project.

**Comment by Player256** [comment]
\assign

**Comment by aditygrg2** [comment]
Hey @zhx828 I want to contribute to this project. Please let me know how I can start and some issues to know the problem better. Thank you!

**Comment by VenkatMastercoder** [comment]
Hey, @zhx828 @inodb @ckandoth @cannin I found this issue to be very interesting. I am interested in contributing to this project, please let me know how I can start and what issues I need to address in order to better understand the problem. Thank you very much!

**Comment by zhx828** [comment]
Hi @Player256 @aditygrg2 @VenkatMastercoder , thank you for your interests. To work on this issue, the following links would be helpful to you.
- This is the original implementation of the tool using Angular https://github.com/oncokb/matchminer-curate
- This is the main website where CTML is defined and used https://matchminer.org/#ctml
- We want to develop this component in React and it should be used anywhere. You could consider set up your own react website using [create-react-app](https://github.com/facebook/create-react-app), or create within [oncokb-public website](https://github.com/oncokb/oncokb-public)

**Comment by tamal78** [comment]
hey @zhx828 I am done with the above steps.Now are there any small good first issue i can contribute.Or should i start with the proposal?

**Comment by zhx828** [comment]
Since this will be an indepandant component, I don't think you need to get familiar with the main code base. But if you want to, here is the list of good first issues. https://github.com/oncokb/oncokb/labels/good%20first%20issue

**Comment by tamal78** [comment]
yeah right i am currently focusing on the matchminer ,CTML only so i can skip the issues.so we will refactor the angular to react component right so that other projects can use this.right?

**Comment by zhx828** [comment]
I created a [branch of matchminer-curate](https://github.com/oncokb/matchminer-curate/tree/gsoc) for GSoC usage. It will only start a frontend component.
To see the example trials, please [slack me ](https://slack.cbioportal.org/) your google email. I will add you to the firebase playground. Then you just need to add an environment.ts file in this folder https://github.com/oncokb/matchminer-curate/tree/gsoc/src/main/webapp/app/environments I will provide all connection strings too to update this file.

**Comment by Coderner** [comment]
Hii @zhx828 I am Shreya Shukla, a pre final year student pursuing a bachelor's degree in Computer Science and Engineering. I am a ReactJs developer and love create interactive UIs. I have familiarised myself with CTML and Matchminer. I have started working with my proposal. Kindly suggest me if there is anything I am missing out or must do before submitting my proposal.

**Comment by zhx828** [comment]
In light of https://github.com/cBioPortal/GSoC/issues/103 , this project is no longer active.
