### ISSUE TITLE
(Group Comparison) Generic Assay Categorical/Binary data implementation

### ISSUE THREAD

**Issue by dippindots** [cBioPortal/GSoC#97]
**Background**: 

- **cBioPortal:** cBioPortal is an open-source platform for cancer genomics data analysis and visualization. It provides a centralized resource for exploring and analyzing large-scale cancer genomic data sets, including genomic alterations, gene expression, and clinical information. The platform integrates data from multiple sources, including The Cancer Genome Atlas (TCGA) and the International Cancer Genome Consortium (ICGC), and makes it available through a web interface for researchers, clinicians, and the general public. Please refer to the [cBioPortal](www.cbioportal.org) home page for an overview.
- **Project:** The project aims to implement the Generic Assay Categorical/Binary data feature in the cBioPortal group comparison tab and group comparison page. The feature will allow users to analyze and visualize categorical and binary data in the context of cancer genomics.
- **Group Comparison:** The group comparison feature in cBioPortal is a useful tool for cancer researchers to gain insights into the underlying biology of cancer and to identify potential targets for therapeutic intervention. It allows users to compare molecular data between two or more groups of samples in a cancer study. This feature enables researchers to identify genomic alterations, gene expression patterns, and clinical traits that are significantly different between groups. Users can define the groups of samples based on patient attributes such as diagnosis, treatment, and survival, or based on molecular characteristics such as gene expression, copy number alterations, or mutation status. The results of the comparison are displayed in various types of plots and tables, such as bar charts, heat maps, and contingency tables, that allow users to visualize and analyze the data. Additionally, users can access gene-level information, including gene summaries, protein interactions, and relevant publications, to help interpret the results of the comparison.

**Goal**: 

The goal of this project is to enhance the functionality of cBioPortal by adding support for the analysis and visualization of categorical and binary data in [Generic Assay format](https://docs.cbioportal.org/file-formats/#generic-assay). This will allow users to perform Fisher's exact test for binary data and chi-square test for categorical data, and to view the results in a clear and easy-to-understand format.
- Implement Generic Assay Categorical/Binary feature in both the Group Comparison page and Group Comparison tab (Results view page)
  - Binary data:  
![image](https://user-images.githubusercontent.com/15748980/217416577-4d7213f8-5ecd-4279-940c-a4d0a3e1d501.png)
  - Categorial data:    
![image](https://user-images.githubusercontent.com/15748980/217416653-b6d33b30-43c9-41f3-977a-84b0222ce259.png)

- Adding end-to-end tests to validate the feature is working as expected

**Approach**: 

The project will involve the following steps:

- (Frontend) See if it's possible to calculate values in the backend, otherwise Implement Fisher's exact test for binary data and the chi-square test for categorical data.
- (Backend) Implement new Services and Controller to provide needed data for the frontend
- (Frontend) Implement features in
  -  comparison page
  -  comparison tab in results
- (Frontend) Add the ability to view the results of these tests in the comparison tab and group comparison page in cBioPortal.
- (Frontend) Ensure that the results are displayed in a clear and easy-to-understand format, similar to the Mutations tab and Clinical tab in cBioPortal.
- (Frontend/ Backend)Add end-to-end tests for this feature

**Need skills**: 
JavaScript, Java, SQL

**Possible mentors**: 
@dippindots @inodb @alisman @onursumer

**Comment by Sakshamgupta90** [comment]
Hi, I want to work on this one, looking forward for more details :)

**Comment by riyavnitk** [comment]
Hi! I would like to contribute to this project, looking forward to it !

**Comment by Shamloor** [comment]
Hello! I am interested in this project, and I hope to participate in it.

**Comment by Shamloor** [comment]
Hi! I'm Willson a student. I have some experience in Java, JavaScript, Hadoop and MySQL. I would like to work on this task. Is this task still available?

**Comment by dippindots** [comment]
Dear @Sakshamgupta90, @riyavnitk, and @Shamloor,

Welcome to the cBioPortal community. Our team is currently working diligently to prepare a more detailed overview of the project. In the meantime, it's highly recommended that you explore our available resources, including our informative webinar recordings, which can be found at [webinar recordings](https://docs.cbioportal.org/user-guide/overview/#webinar-recordings). You can also find an introduction to the Group Comparison feature in section 4 of our user guide.

Rest assured that once we have finalized the details of this project, we will update this space and keep everyone notified. Thank you for your interest!

**Comment by harsh2929** [comment]
hello @dippindots , is the issue still up for contribution then kindly add me too

**Comment by LydiaKip** [comment]
Hello @dippindots , 
My name is Lydia, currently a second year student taking CS. I am interested in working in this project. I have experience in Java, SQL and JavaScript. Although it's late can I submit my proposal to be reviewed ?

**Comment by dippindots** [comment]
@LydiaKip Of course, it's not too late, please feel free to submit your proposal.

**Comment by inodb** [comment]
this has been implemented and merged
