### ISSUE TITLE
Show alteration frequencies for groups in OncoPrints

### ISSUE THREAD

**Issue by inodb** [cBioPortal/GSoC#99]
**Background**: 

- **cBioPortal:** cBioPortal is an open-source platform for cancer genomics data analysis and visualization. It provides a centralized resource for exploring and analyzing large-scale cancer genomic data sets, including genomic alterations, gene expression, and clinical information. The platform integrates data from multiple sources, including The Cancer Genome Atlas (TCGA) and the International Cancer Genome Consortium (ICGC), and makes it available through a web interface for researchers, clinicians, and the general public. Please refer to the [cBioPortal](www.cbioportal.org) home page for an overview.
- **OncoPrint:** The OncoPrint is a heatmap-like chart that shows what genomic alterations are present in a cohort. It is one of the most popular visualizations in cBioPortal. 

    ![Screen Shot 2023-02-08 at 3 50 36 PM](https://user-images.githubusercontent.com/1334004/217648039-3b21c99a-23d6-45c8-b4cd-ed5697419190.png)

    In the figure above the OncoPrint shows one column per patient and one row for each gene (KRAS/NRAS/BRAF). Each glyph shows you what type of alteration is happening in that specific patient's tumor. The example here shows a cohort of colorectal cancer patients and it is noticeable that the mutations are mutually exclusive across the KRAS, NRAS and BRAF genes. You can interactively explore this example [here](https://www.cbioportal.org/results?cancer_study_list=coadread_tcga_pub&cancer_study_id=coadread_tcga_pub&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=coadread_tcga_pub_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=coadread_tcga_pub_gistic&Z_SCORE_THRESHOLD=2.0&case_set_id=coadread_tcga_pub_nonhypermut&gene_list=KRAS%20NRAS%20BRAF&gene_set_choice=user-defined-list). 

- **Project:** OncoPrints currently support the visual separation of groups, as defined by clinical data elements in annotation tracks (via the "Show gaps" option in the Annotation track menu), see this example:
https://bit.ly/3IaS8YZ

  A missing feature is to indicate the alteration frequencies of the individual groups, like in this example from [Chatila et al.](https://doi.org/10.1038/s41467-022-35592-9):
  <img width="1161" alt="image" src="https://user-images.githubusercontent.com/11892704/217575587-25ded557-78c7-4bf2-acb8-77a5ae4c8d44.png">

**Goal**: Show alteration frequencies per group

**Approach**:   We could add a new menu item in the settings menu for the track, e.g.: "Show alteration frequencies of each group"
  <img width="689" alt="image" src="https://user-images.githubusercontent.com/11892704/217576034-37524635-cee1-406a-892f-789c2c485c7e.png">

**Need skills**: 
- JavaScript, React

**Possible mentors**: 
@inodb @gblaih @alisman

**Comment by makovstanislav** [comment]
Hello 👋 Thanks for sharing this project. I would be highly interested working on it. Waiting for the publishing of organisations list to send a proposal.

**Comment by Abinash-bit** [comment]
@inodb Hlo I am intrested in solving this issue please guide me.

**Comment by singhvaibhav924** [comment]
Hey, I am finding this issue quite interesting as well as challenging can anyone please help me from where to start .....

**Comment by kts-desilva** [comment]
Hi @inodb , I am interested in solving this issue as a frequent user of cbioPortal. Please guide me on the steps to start.

**Comment by eshan-003** [comment]
Hi @inodb , i am well versed in MERN stack and web dev in general . I came across this project and feel that i can contribute to this.Plz guide me on the steps to start

**Comment by Ruthu364** [comment]
Hi @inodb ,i am interested in this project.plds guide me to start

**Comment by hendsaeedd** [comment]
Hi @inodb ,i am interested in this project.

**Comment by sawaisinghh** [comment]
Hi @inodb, I know this tech stack very well. So, I feel like i can solve this issue.

**Comment by Danish-Belal** [comment]
Hello @inodb  can i work on this issue   ? Kindly assign to me.

**Comment by Sudesha-STR** [comment]
Hello @inodb, I am finding this issue quite interesting. Can you please assign it to me?

**Comment by farmannaseem** [comment]
**Hi! Can I Work on this issue ?
IF Yes Then Assign me This Issue 
Thank you!! :)**

**Comment by inodb** [comment]
Hi all - please take at running the frontend: https://github.com/cBioPortal/cbioportal-frontend. Feel free to reach out on [slack](slack.cbioportal.org) for further questions

**Comment by gaurab-khanal** [comment]
> Hi all - please take at running the frontend: https://github.com/cBioPortal/cbioportal-frontend. Feel free to reach out on [slack](slack.cbioportal.org) for further questions

I can't get invitation for slack. Can you sent me? email - khanalgaurab98@gmail.com

**Comment by inodb** [comment]
@gaurab-khanal it looks like you're already part of the workspace. Are you able to log in on https://cbioportal-public.slack.com?

**Comment by gaurab-khanal** [comment]
> @gaurab-khanal it looks like you're already part of the workspace. Are you able to log in on https://cbioportal-public.slack.com?

Yes I did.

**Comment by HarounTheGreat** [comment]
Greetings, I'd want to contribute to this problem. Would you kindly direct me?

**Comment by OmkarBorker** [comment]
Hello @inodb i am interested in this issue and would like to contribute to this issue.Kindly direct me?

**Comment by seifbhxc65** [comment]
hi @inodb  how can i be part of the slack portal?

**Comment by inodb** [comment]
@seifbhxc65 you can sign up at slack.cbioportal.org

**Comment by alisman** [comment]
Move to https://github.com/cBioPortal/cbioportal/issues/10295
